! ----------------------------------------------------------------------
!   This file is a part of EFDC+
!   Website:  https://eemodelingsystem.com/
!   Repository: https://github.com/dsi-llc/EFDC_Plus.git
! ----------------------------------------------------------------------
! Copyright 2021-2022 DSI, LLC
! Distributed under the GNU GPLv2 License.
! ----------------------------------------------------------------------
SUBROUTINE VARALLOC

  !----------------------------------------------------------------------!
  ! CHANGE RECORD
  ! DATE MODIFIED     BY               DESCRIPTION
  !----------------------------------------------------------------------!
  !    2015-06       PAUL M. CRAIG     IMPLEMENTED SIGMA-Z (SGZ) IN EE7.3

  USE GLOBAL
  Use Allocate_Initialize
  USE HYDSTRUCMOD
  Use Variables_WQ
  
  USE MPI
  USE Variables_MPI
  Use Broadcast_Routines
  Use ifport

  IMPLICIT NONE

  INTEGER :: L, ierr
  Integer :: NS, lower_bound, upper_bound
  Logical Test
  
  ! *** Only write to LOG file from the master process
  if( process_id == master_id  )THEN
    WRITE(*, '(A)')'ALLOCATING ARRAYS'
  End if

  ! *** Write arrays sizes to file
  Call Write_Array_Sizes
  Call MPI_Barrier(comm_2d, ierr)

  ! *** Calculates max size of some arrays
  NMAXBC = MDCHH*2 + NQSIJ + NQCTL*2 + NQWR*2 + NPBS + NPBW + NPBE + NPBN + NQJPIJ*2

  ! *** Need to broadcast NMAXBC size of arrays to each process so they can allocate arrays of the correct size
  Call broadcast_scalar_int(NMAXBC, master_id)

  Allocate(Map2Global(LCM))
  Allocate(Map2Local(LCM_Global))

  ! *** Character arrays
  Allocate(CLTMSR(MLTMSRM))
  Allocate(CLSL(MLM))
  Allocate(SYMBOL(MTM))
  CLSL = ' '
  CLTMSR = ' '
  SYMBOL = ' '
  
  ! *** Special Range arrays
  Allocate(LIJ(-1:ICM,    -1:JCM))
  Allocate(LIJLT(-1:ICM,  -1:JCM))
  Allocate(IJCT(-1:ICM,   -1:JCM))
  Allocate(IJCTLT(-1:ICM, -1:JCM))
  LIJ = 0
  LIJLT = 0
  IJCT = 0
  IJCTLT = 0
  
  ! *** Type Structures
  IF( ISTRAN(3) > 0 .AND. NDYE > 0 )THEN
    Allocate(DYES(NDYE))
  ENDIF
  Allocate(WV(LCM))

  Allocate(HYD_STR_GL(NQCTL))   ! *** Hydraulic structure controls
  Allocate(HSCTL_GL(NQCTL))     ! *** Hydraulic structure controls
  
  ALLOCATE(WITH_RET_GL(NQWR))   ! *** Withdrawal-Return
  ALLOCATE(WRCTL_GL(NQWR))      ! *** Withdrawal-Return
  
  ! *** Each process allocates their own variable
  Call AllocateDSI( AAU,        LCM,        0.0)     
  Call AllocateDSI( AAV,        LCM,        0.0)     
  Call AllocateDSI( AB,         LCM,        KCM,     0.0)
  Call AllocateDSI( ACCWX,      MTM,        0.0)     
  Call AllocateDSI( AGWELV,     LCM,        0.0)                ! *** GROUNDWATER INTERACTION WITH CELL WATER ELEVATION (M) IF ISGWIE >= 1
  Call AllocateDSI( AGWELV1,    LCM,        0.0)     
  Call AllocateDSI( AGWELV2,    LCM,        0.0)     
  Call AllocateDSI( AH,         LCM,        KCM,     0.0)
  Call AllocateDSI( AHC,        LCM,        KCM,     0.0)
  Call AllocateDSI( AHDXY,      LCM,        0.0)     
  Call AllocateDSI( AHOXY,      LCM,        0.0)     
  Call AllocateDSI( AHU,        LCM,        KCM,     0.0)       ! *** NOT USED  DELME - CAN BE USED FOR DEBUGGING
  Call AllocateDSI( AHV,        LCM,        KCM,     0.0)       ! *** NOT USED  DELME - CAN BE USED FOR DEBUGGING
  Call AllocateDSI( AP,         KPCM,       0.0)     
  Call AllocateDSI( APCG,       LCM,        0.0)     
  Call AllocateDSI( APT,        KPCM,       KCM,     0.0)
  Call AllocateDSI( AQ,         LCM,        KCM,     0.0)
  Call AllocateDSI( AQCTL,      NQCTTM,     0.0)     
  Call AllocateDSI( ASURFEL,    LCM,        0.0)     
  Call AllocateDSI( ATMP,       LCM,        0.0)     
  Call AllocateDSI( AV,         LCM,        KCM,     0.0)
  Call AllocateDSI( AVOXY,      LCM,        0.0)     
  Call AllocateDSI( AVBXY,      LCM,        0.0)     
  Call AllocateDSI( AVUI,       LCM,        KCM,     0.0)
  Call AllocateDSI( AVVI,       LCM,        KCM,     0.0)
  Call AllocateDSI( B,          LCM,        KCM,     0.0)
  Call AllocateDSI( B1,         LCM,        KCM,     0.0)
  Call AllocateDSI( BBU,        LCM,        0.0)     
  Call AllocateDSI( BBV,        LCM,        0.0)     
  Call AllocateDSI( BCLSHA,     KCM,        MLM,     MTM,  0.0)
  Call AllocateDSI( BELAGW,     LCM,        0.0)     
  Call AllocateDSI( BELSURF,    LCM,        0.0)     
  Call AllocateDSI( BELV,       LCM,        0.0)     
  Call AllocateDSI( BELV0,      LCM,        0.0)     
  Call AllocateDSI( BELV1,      LCM,        0.0)     
  Call AllocateDSI( BLSHA,      KCM,        MLM,     0.0)
  Call AllocateDSI( BSLSHA,     KCM,        MLM,     MTM,  0.0)
  Call AllocateDSI( BTLSHA,     KCM,        MLM,     0.0)
  Call AllocateDSI( BTMP,       KCM,        0.0)     
  Call AllocateDSI( CAC,        LCM,        KCM,     0.0)
  Call AllocateDSI( CBE,        NBBEM,      2,       NSTVM2,0.0)
  Call AllocateDSI( CBN,        NBBNM,      2,       NSTVM2,0.0)
  Call AllocateDSI( CBS,        NBBSM,      2,       NSTVM2,0.0)
  Call AllocateDSI( CBW,        NBBWM,      2,       NSTVM2,0.0)
  Call AllocateDSI( CC,         LCM,        0.0)
  Call AllocateDSI( CCC,        LCM,        0.0)
  Call AllocateDSI( CCCC,       MTM,        0.0)
  Call AllocateDSI( CCCCHH,     NCHANM,     0.0)
  Call AllocateDSI( CCCCHU,     NCHANM,     0.0)
  Call AllocateDSI( CCCCHV,     NCHANM,     0.0)
  Call AllocateDSI( CCCI,       LCM,        0.0)
  Call AllocateDSI( CCCOS,      MTM,        0.0)
  Call AllocateDSI( CCCOS1,     MTM,        0.0)
  Call AllocateDSI( CCE,        LCM,        0.0)
  Call AllocateDSI( CCI,        LCM,        0.0)
  Call AllocateDSI( CCLSHA,     MTM,        MTM, 0.0)
  Call AllocateDSI( CCN,        LCM,        0.0)
  Call AllocateDSI( CCNHTT,     LCM,        0.0)                           ! *** WIND FUNCTION FOR CONDUCTIVE HEAT TRANSFER
  Call AllocateDSI( CCS,        LCM,        0.0)
  Call AllocateDSI( CCW,        LCM,        0.0)
  Call AllocateDSI( CDZKK,      LCM,        KCM, 0.0)
  Call AllocateDSI( CDZKKP,     LCM,        KCM, 0.0)
  Call AllocateDSI( CDZKMK,     LCM,        KCM, 0.0)
  Call AllocateDSI( CE,         LCM,        0.0)
  Call AllocateDSI( CFRD,       NQJPM,      0.0)
  Call AllocateDSI( CHANFRIC,   NCHANM,     0.0)
  Call AllocateDSI( CHANLEN,    NCHANM,     0.0)
  Call AllocateDSI( CLEVAP,     LCM,        0.0)                        ! *** WIND FUNCTION FOR EVAPORATION CALCULATIONS
  Call AllocateDSI( CLOE,       NBBEM,      KCM,     NSTVM2, 0.0)
  Call AllocateDSI( CLON,       NBBNM,      KCM,     NSTVM2, 0.0)
  Call AllocateDSI( CLOS,       NBBSM,      KCM,     NSTVM2, 0.0)
  Call AllocateDSI( CLOUDT,     LCM, 0.0  )                  
  Call AllocateDSI( CLOW,       NBBWM,      KCM,     NSTVM2, 0.0)
  Call AllocateDSI( CLSHA,      MTM,        0.0)             
  Call AllocateDSI( CMB,        KCM,        0.0)             
  Call AllocateDSI( CN,         LCM,        0.0)             
  Call AllocateDSI( CONGW,      LCM,        NSTVM2,    0.0)  
  Call AllocateDSI( CONT,       LCM,        KCM,       0.0)  
  Call AllocateDSI( CPFAM0,     NPFORM,     MTM,       0.0)  
  Call AllocateDSI( CPFAM1,     NPFORM,     MTM,       0.0)  
  Call AllocateDSI( CPFAM2,     NPFORM,     MTM,       0.0)  
  Call AllocateDSI( CQCJP,      KCM,        NQJPM,  -NSTVM2, 0.0)
  Call AllocateDSI( CQS,        KCM,        NQSIJM,  NSTVM2, 0.0)
  Call AllocateDSI( CQSE,       NSTVM2,     0.0)     
  Call AllocateDSI( CQWR,       NQWRM,      NSTVM2,    0.0)
  Call AllocateDSI( CQWRSER,    NDQWRSR,    NQWRSRM, NSTVM2, 0.0)
  Call AllocateDSI( CQWRSERT,  -NQWRSRM,    NSTVM2,    0.0)
  Call AllocateDSI( CS,         LCM,        0.0)
  Call AllocateDSI( CSERT,      KCM,       -NCSERM, -NSTVM2, 0.0)
  Call AllocateDSI( CSLSHA,     MTM,        MTM,       0.0)
  Call AllocateDSI( CTAUC,      LCM,        0.0)
  Call AllocateDSI( CTLSHA,     MTM,        0.0)
  Call AllocateDSI( CTURBB1,    LCM,        KCM,     0.0)
  Call AllocateDSI( CTURBB2,    LCM,        KCM,     0.0)
  Call AllocateDSI( CU1,        LCM,        KCM,     0.0)
  Call AllocateDSI( CU2,        LCM,        KCM,     0.0)
  Call AllocateDSI( CUE,        LCM,        0.0)
  Call AllocateDSI( CUN,        LCM,        0.0)
  Call AllocateDSI( CUU,        LCM,        0.0)
  Call AllocateDSI( CVE,        LCM,        0.0)
  Call AllocateDSI( CVN,        LCM,        0.0)
  Call AllocateDSI( CVV,        LCM,        0.0)
  Call AllocateDSI( CW,         LCM,        0.0)
  Call AllocateDSI( CWRCJP,     NQJPM,    -NSTVM2,   0.0)
  Call AllocateDSI( DJET,       NQJPM,      0.0)
  Call AllocateDSI( DJPER,      NQJPM,      0.0)
  Call AllocateDSI( DLAT,       LCM,        0.0)
  Call AllocateDSI( DLON,       LCM,        0.0)
  Call AllocateDSI( DML,        LCM,       -KCM,      0.0)
  Call AllocateDSI( DTAUC,      NTSM,       0.0)      
  Call AllocateDSI( DU,         LCM,        KCM,      0.0)
  Call AllocateDSI( DV,         LCM,        KCM,      0.0)
  Call AllocateDSI( DXDJ,       LCM,        0.0)
  Call AllocateDSI( DXFP,       LCM,        0.0)
  Call AllocateDSI( DXIU,       LCM,        0.0)
  Call AllocateDSI( DXIV,       LCM,        0.0)
  Call AllocateDSI( DXP,        LCM,        0.0)
  Call AllocateDSI( DXU,        LCM,        0.0)
  Call AllocateDSI( DXV,        LCM,        0.0)
  Call AllocateDSI( DXXTCA,     LCM,        0.0)
  Call AllocateDSI( DXYIP,      LCM,        0.0)
  Call AllocateDSI( DXYIU,      LCM,        0.0)
  Call AllocateDSI( DXYIV,      LCM,        0.0)
  Call AllocateDSI( DXYP,       LCM,        0.0)
  Call AllocateDSI( DXYTCA,     LCM,        0.0)
  Call AllocateDSI( DXYU,       LCM,        0.0)
  Call AllocateDSI( DXYV,       LCM,        0.0)
  Call AllocateDSI( DYDI,       LCM,        0.0)
  Call AllocateDSI( DYE,        LCM,        KCM,      NDYM, 0.0)
  Call AllocateDSI( DYE1,       LCM,        KCM,      NDYM, 0.0)
  Call AllocateDSI( DYEINIT,    LCM,        KCM,      NDYM, 0.0)
  Call AllocateDSI( DYFP,       LCM,        0.0)     
  Call AllocateDSI( DYIU,       LCM,        0.0)     
  Call AllocateDSI( DYIV,       LCM,        0.0)     
  Call AllocateDSI( DYP,        LCM,        0.0)     
  Call AllocateDSI( DYU,        LCM,        0.0)     
  Call AllocateDSI( DYV,        LCM,        0.0)     
  Call AllocateDSI( DZIC,       LCM,       -KCM,      0.0)
  Call AllocateDSI( DZIG,       LCM,       -KCM,      0.0)
  Call AllocateDSI( EVAPGW,     LCM,        0.0)                     ! *** TRANSPIRATION RATE OF WATER PER CELL (M3/S)
  Call AllocateDSI( EVAPSW,     LCM,        0.0)                     ! *** EVAPORATION RATE OF WATER PER CELL (M3/S)
  Call AllocateDSI( EVAPT,      LCM,        0.0)                     ! *** EVAPORATION RATE OF WATER PER CELL (M/S)
  Call AllocateDSI( FACBEDL,    LCM,        0.0)      
  Call AllocateDSI( FACSUSL,    LCM,        0.0)      
  Call AllocateDSI( FBBX,       LCM,        KCM,      0.0)
  Call AllocateDSI( FBBY,       LCM,        KCM,      0.0)
  IF( ISBODYF == 1 )THEN                             
    Call AllocateDSI( FBODYFX,   LCM,       KCM,      0.0)
    Call AllocateDSI( FBODYFY,   LCM,       KCM,      0.0)
  ENDIF                                             
  Call AllocateDSI( FCAX,       LCM,        KCM,      0.0)
  Call AllocateDSI( FCAXE,      LCM,        0.0)      
  Call AllocateDSI( FCAY,       LCM,        KCM,      0.0)
  Call AllocateDSI( FCAY1,      LCM,        KCM,      0.0)
  Call AllocateDSI( FCAY1E,     LCM,        0.0)      
  Call AllocateDSI( FCAYE,      LCM,        0.0)      
  Call AllocateDSI( FCORC,      LCM,        0.0)      
  Call AllocateDSI( FP,         LCM,        0.0)      
  Call AllocateDSI( FP1,        LCM,        0.0)      
  Call AllocateDSI( FPGXE,      LCM,        0.0)      
  Call AllocateDSI( FPGYE,      LCM,        0.0)      
  Call AllocateDSI( PMCTESTX,   10,         LCM,      0.0)   ! *** CREATED AND ALLOCATED FOR DEBUG ASSIGNMENTS - NOT USED FOR ROUTINE RUNS
  Call AllocateDSI( PMCTESTY,   10,         LCM,      0.0)   ! *** CREATED AND ALLOCATED FOR DEBUG ASSIGNMENTS - NOT USED FOR ROUTINE RUNS
  Call AllocateDSI( FPROX,      LCM,       -KCM,      0.0)
  Call AllocateDSI( FPTMP,      LCM,        0.0)      
  Call AllocateDSI( FSCORTBCV,  LCM,        0.0)      
  Call AllocateDSI( FUDISP,     KCM,        LCM,      0.0)
  Call AllocateDSI( FUHDYE,     LCM,        0.0)      
  Call AllocateDSI( FUHU,       LCM,        KCM,      0.0)
  Call AllocateDSI( FUHV,       LCM,        KCM,      0.0)
  Call AllocateDSI( FVHDXE,     LCM,        0.0)      
  Call AllocateDSI( FVHU,       LCM,        KCM,      0.0)
  Call AllocateDSI( FVHV,       LCM,        KCM,      0.0)
  Call AllocateDSI( FWQQ,       LCM,        KCM,      0.0)
  Call AllocateDSI( FWQQL,      LCM,        KCM,      0.0)
  Call AllocateDSI( FWU,        LCM,       -KCM,      0.0)
  Call AllocateDSI( FWV,        LCM,       -KCM,      0.0)
  Call AllocateDSI( FX,         LCM,        KCM,      0.0)
  Call AllocateDSI( FXE,        LCM,        0.0)      
  Call AllocateDSI( FY,         LCM,        KCM,      0.0)
  Call AllocateDSI( FYE,        LCM,        0.0)      
  Call AllocateDSI( FZU,       -KCM,        0.0)      
  Call AllocateDSI( FZV,       -KCM,        0.0)      
  Call AllocateDSI( GAMB,       KCM,        0.0)      
  Call AllocateDSI( GLSHA,      MGM,        MGM,      0.0)
  Call AllocateDSI( GWCSER,     NDGWSER,    NGWSERM,  NSTVM2, 0.0)
  Call AllocateDSI( GWCSERT,   -NGWSERM,   -NSTVM2,   0.0)
  Call AllocateDSI( GWFAC,      LCM,        0.0)      
  Call AllocateDSI( GWSER,      NDGWSER,    NGWSERM,  0.0)
  Call AllocateDSI( GWSERT,    -NGWSERM,    0.0)
  Call AllocateDSI( H1P,        LCM,        0.0)
  Call AllocateDSI( H1U,        LCM,        0.0)
  Call AllocateDSI( H1UI,       LCM,        0.0)
  Call AllocateDSI( H1V,        LCM,        0.0)
  Call AllocateDSI( H1VI,       LCM,        0.0)
  Call AllocateDSI( H2P,        LCM,        0.0)
  Call AllocateDSI( H2WQ,       LCM,        0.0)
  Call AllocateDSI( HBEDA,      LCM,        0.0)
  Call AllocateDSI( HBEDA1,     LCM,        0.0)
  Call AllocateDSI( HCTLDA,     NQCTTM,     0.0)
  Call AllocateDSI( HCTLDM,     NQCTTM,     0.0)
  Call AllocateDSI( HCTLUA,     NQCTTM,     0.0)
  Call AllocateDSI( HCTLUM,     NQCTTM,     0.0)
  Call AllocateDSI( HDFUFX,     LCM,        0.0)
  Call AllocateDSI( HDFUFY,     LCM,        0.0)
  Call AllocateDSI( HDFUF,      LCM,        0.0)
  Call AllocateDSI( HDIFCTD,    NDQCLT,     NQCTTM,   0.0)
  Call AllocateDSI( HDIFCTL,    NDQCLT,     NQCTTM,   0.0)
  Call AllocateDSI( HGDH,       LCM,        0.0)
  Call AllocateDSI( HMP,        LCM,        0.0)
  Call AllocateDSI( HMPW,       LCM,        0.0)
  Call AllocateDSI( HMU,        LCM,        0.0)
  Call AllocateDSI( HMUW,       LCM,        0.0)
  Call AllocateDSI( HMV,        LCM,        0.0)
  Call AllocateDSI( HMVW,       LCM,        0.0)
  Call AllocateDSI( HP,         LCM,        0.0)
  Call AllocateDSI( HPI,        LCM,        0.0)
  Call AllocateDSI( HPTMP,      LCM,        0.0)
  Call AllocateDSI( HRU,        LCM,        0.0)
  Call AllocateDSI( HRUO,       LCM,        0.0)            ! *** U INTERFACE METRIC (DY AT THE U FACE) / (DX AT THE U FACE) [DYU(L)*DXIU(L)] (DIMENSIONLESS)
  Call AllocateDSI( HRV,        LCM,        0.0)
  Call AllocateDSI( HRVO,       LCM,        0.0)            ! *** V INTERFACE METRIC (DX AT THE V FACE) / (DY AT THE V FACE) [DXV(L)*DYIV(L)] (DIMENSIONLESS)
  Call AllocateDSI( HTMP,       LCM,        0.0)
  Call AllocateDSI( HU,         LCM,        0.0)
  Call AllocateDSI( HUDRY,      LCM,        0.0)
  Call AllocateDSI( HUI,        LCM,        0.0)
  Call AllocateDSI( HUTMP,      LCM,        0.0)
  Call AllocateDSI( HUWET,      LCM,        0.0)
  Call AllocateDSI( HV,         LCM,        0.0)
  Call AllocateDSI( HVDRY,      LCM,        0.0)
  Call AllocateDSI( HVI,        LCM,        0.0)
  Call AllocateDSI( HVTMP,      LCM,        0.0)
  Call AllocateDSI( HVWET,      LCM,        0.0)
  Call AllocateDSI( HWQ,        LCM,        0.0)
  Call AllocateDSI( HWQI,       LCM,        0.0)
                                         
  Call AllocateDSI( GRPID,      NQSIJM,       0)
  Call AllocateDSI( IACTLR,     NGLM,         0)
  Call AllocateDSI( IAIJ,       IGM,        JGM,      0)
  Call AllocateDSI( IAKL,       KPCM,       LCM,      0)
  Call AllocateDSI( IAP,        KPCM,         0)      
  Call AllocateDSI( ICALJP,     NQJPM,        0)      
  Call AllocateDSI( ICBE,       NBBEM,        0)      
  Call AllocateDSI( ICBN,       NBBNM,        0)      
  Call AllocateDSI( ICBS,       NBBSM,        0)      
  Call AllocateDSI( ICBW,       NBBWM,        0)      
  Call AllocateDSI( ICFLMP,     LCM,          0)      
  Call AllocateDSI( ICSMTS,     NTSSMVM, NSMTSM,      0)
  Call AllocateDSI( IGWSER,    -NGWSERM,      0)
  Call AllocateDSI( IL,         LCM,          0)
  Call AllocateDSI( ILLSHA,     MLM,          0)
  Call AllocateDSI( ILLT,       LCM,          0)
  Call AllocateDSI( ILTMSR,     MLTMSRM,      0)
  !ALLOCATE(IMASKDRY(LCM, 0. 0 )                        ! *** DEPRECATED - NO LONGER USED 2015-02
  Call AllocateDSI( IMDCHH,     NCHANM,       0)
  Call AllocateDSI( IMDCHU,     NCHANM,       0)
  Call AllocateDSI( IMDCHV,     NCHANM,       0)
  Call AllocateDSI( INTPSER,    NPSERM,       0)
  Call AllocateDSI( IOUTJP,     NQJPM,        0)
  Call AllocateDSI( IPART,      LCM,          0)
  
  Call AllocateDSI( IPBE,       NPBEM,        0)
  Call AllocateDSI( IPBN,       NPBNM,        0)
  Call AllocateDSI( IPBS,       NPBSM,        0)
  Call AllocateDSI( IPBW,       NPBWM,        0)
  
  Call AllocateDSI( IQJP,       NQJPM,        0)
  Call AllocateDSI( IQS,        NQSIJM,       0)
  Call AllocateDSI( ISCDRY,     LCM,          0)
  Call AllocateDSI( ISDJP,      NQJPM,        0)
  Call AllocateDSI( ISENT,      NQJPM,        0)
  
  Call AllocateDSI( ISPBE,      NPBEM,        0)
  Call AllocateDSI( ISPBN,      NPBNM,        0)
  Call AllocateDSI( ISPBS,      NPBSM,        0)
  Call AllocateDSI( ISPBW,      NPBWM,        0)
  
  Call AllocateDSI( ISPRE,      NPBEM,        0)
  Call AllocateDSI( ISPRN,      NPBNM,        0)
  Call AllocateDSI( ISPRS,      NPBSM,        0)
  Call AllocateDSI( ISPRW,      NPBWM,        0)
  
  Call AllocateDSI( ISSBCP,     LCM,          0)
  Call AllocateDSI( ISTJP,      NQJPM,        0)
  Call AllocateDSI( ISUDPC,     NCHANM,       0)
  Call AllocateDSI( IUPCJP,     NQJPM,        0)
  Call AllocateDSI( IWGG,       NWGGM,        0)
  
  Call AllocateDSI( JCBE,       NBBEM,        0)
  Call AllocateDSI( JCBN,       NBBNM,        0)
  Call AllocateDSI( JCBS,       NBBSM,        0)
  Call AllocateDSI( JCBW,       NBBWM,        0)
  
  Call AllocateDSI( JL,         LCM,          0)
  Call AllocateDSI( JLLSHA,     MLM,          0)
  Call AllocateDSI( JLLT,       LCM,          0)
  Call AllocateDSI( JLTMSR,     MLTMSRM,      0)
  Call AllocateDSI( JMDCHH,     NCHANM,       0)
  Call AllocateDSI( JMDCHU,     NCHANM,       0)
  Call AllocateDSI( JMDCHV,     NCHANM,       0)
  
  Call AllocateDSI( JPBE,       NPBEM,        0)
  Call AllocateDSI( JPBN,       NPBNM,        0)
  Call AllocateDSI( JPBS,       NPBSM,        0)
  Call AllocateDSI( JPBW,       NPBWM,        0)
  
  Call AllocateDSI( JQJP,       NQJPM,        0)
  Call AllocateDSI( JQS,        NQSIJM,       0)
  Call AllocateDSI( JUPCJP,     NQJPM,        0)
  Call AllocateDSI( JWGG,       NWGGM,        0)
  Call AllocateDSI( KBT,        LCM,          0)
  Call AllocateDSI( KCEFDC,     LCM*KCM,      0)
  Call AllocateDSI( KEFFJP,     NQJPM,        0)
  Call AllocateDSI( KFEFDC,     2*LCM*KCM,    0)
  Call AllocateDSI( KPS,        LCM,          0)
  Call AllocateDSI( KQJP,       NQJPM,        0)
  Call AllocateDSI( KUPCJP,     NQJPM,        0)
  Call AllocateDSI( KUPW,       LCM,        KCM,      0)
  Call AllocateDSI( LBERC,      NMAXBC,       0)
  Call AllocateDSI( LBNRC,      NMAXBC,       0)
  Call AllocateDSI( LBSRC,      NMAXBC,       0)
  Call AllocateDSI( LBWRC,      NMAXBC,       0)
  
  Call AllocateDSI( LCBE,       NBBEM,        0)
  Call AllocateDSI( LCBN,       NBBNM,        0)
  Call AllocateDSI( LCBS,       NBBSM,        0)
  Call AllocateDSI( LCBW,       NBBWM,        0)
  
  Call AllocateDSI( LCONSOL,    LCM,          0)
  Call AllocateDSI( LCT,        LCM,          0)
  Call AllocateDSI( LCTLT,      LCM,          0)
  Call AllocateDSI( LEC,        LCM,          0)
  Call AllocateDSI( LECLT,      LCM,          0)
  Call AllocateDSI( LJUNX,      NJUNXM,       0)
  Call AllocateDSI( LJUNY,      NJUNYM,       0)
  Call AllocateDSI( LLBC,       LCM,          0)
  Call AllocateDSI( LLRC,       LCM,          0)
  Call AllocateDSI( LLSHA,      MLM,          0)
  Call AllocateDSI( LMASKDRY,   LCM,    .false.)
  Call AllocateDSI( LWVMASK,    LCM,    .false.)
  Call AllocateDSI( LMDCHH,     NCHANM,       0)
  Call AllocateDSI( LMDCHU,     NCHANM,       0)
  Call AllocateDSI( LMDCHV,     NCHANM,       0)
  Call AllocateDSI( LOPENBCDRY, LCM,    .false.)
  Call AllocateDSI( LNC,        LCM,          0)
  Call AllocateDSI( LNCLT,      LCM,          0)
  Call AllocateDSI( LNEC,       LCM,          0)
  Call AllocateDSI( LNWC,       LCM,          0)
  Call AllocateDSI( LOBCS,      LCM,          0)
  Call AllocateDSI( LOBCS2,     LCM,          0)
  Call AllocateDSI( LBCS,       NMAXBC,       0)
  Call AllocateDSI( LORDER,     LCM,          0)
  
  Call AllocateDSI( LPBE,       NPBEM,        0)
  Call AllocateDSI( LPBN,       NPBNM,        0)
  Call AllocateDSI( LPBS,       NPBSM,        0)
  Call AllocateDSI( LPBW,       NPBWM,        0)
  
  Call AllocateDSI( LQS,        NQSIJM,       0)
  Call AllocateDSI( LQWRD,      NQWRM,        0)
  Call AllocateDSI( LQWRU,      NQWRM,        0)
  Call AllocateDSI( LSBLBCD,    LCM,          0)
  Call AllocateDSI( LSBLBCU,    LCM,          0)
  Call AllocateDSI( MFDCHZ,     LCM,          0)
  Call AllocateDSI( LSC,        LCM,          0)
  Call AllocateDSI( LSCLT,      LCM,          0)
  Call AllocateDSI( LSEC,       LCM,          0)
  Call AllocateDSI( LSHAB,      MLM,          0)
  Call AllocateDSI( LSHAP,      MLM,          0)
  Call AllocateDSI( LSHAU,      MLM,          0)
  Call AllocateDSI( LSHAUE,     MLM,          0)
  Call AllocateDSI( LSMTS,      NSMTSM,       0)
  Call AllocateDSI( LSWC,       LCM,          0)
  Call AllocateDSI( LUPU,       LCM,       KCM,       0)
  Call AllocateDSI( LUPV,       LCM,       KCM,       0)
  Call AllocateDSI( LWC,        LCM,          0)
  Call AllocateDSI( LWCLT,      LCM,          0)
  Call AllocateDSI( LWGG,       NWGGM,        0)
  Call AllocateDSI( LWVCELL,    LCM,          0)
  Call AllocateDSI( MCNTLR,     NGLM,         0)
  Call AllocateDSI( MCSER,      NCSERM,    NSTVM2,    0)
  Call AllocateDSI( MTSCLAST,   NCSERM,    NSTVM2,    0)
  Call AllocateDSI( MDCHTYP,    NCHANM,               0)
  Call AllocateDSI( MGWSER,     NGWSERM,              0)
  Call AllocateDSI( MTSGWLAST,  NGWSERM,              0)
  Call AllocateDSI( MPSER,      NPSERM,               0)
  Call AllocateDSI( MTSPLAST,   NPSERM,               0)
  Call AllocateDSI( MQCTL,      NQCTTM,               0)
  if( .NOT. Allocated(MQSER) )then                   
    Call AllocateDSI( MQSER,    NQSERM,               0)
  endif                                              
  Call AllocateDSI( MTSQLAST,   NQSERM,               0)
  Call AllocateDSI( MQWRSR,     NQWRSRM,              0)
  Call AllocateDSI( MTSWRLAST,  NQWRSRM,              0)
  Call AllocateDSI( MTMSRA,     MLTMSRM,              0)
  Call AllocateDSI( MTMSRC,     MLTMSRM,              0)
  Call AllocateDSI( MTMSRP,     MLTMSRM,              0)
  Call AllocateDSI( MTMSRQ,     MLTMSRM,              0)
  Call AllocateDSI( MTMSRQE,    MLTMSRM,              0)
  Call AllocateDSI( MTMSRU,     MLTMSRM,              0)
  Call AllocateDSI( MTMSRUE,    MLTMSRM,              0)
  Call AllocateDSI( MTMSRUT,    MLTMSRM,              0)
  Call AllocateDSI( MTSCUR,     NTSSTSPM,             0)
  Call AllocateDSI( MTSSTSP,    NTSSTSPM,             0)
  Call AllocateDSI( MVEGL,      LCM,                  0)
  Call AllocateDSI( MVEGSER,    NVEGSERM,             0)
  Call AllocateDSI( MVEGTLAST,  NVEGSERM,             0)
  Call AllocateDSI( NATDRY,     LCM,                  0)
  Call AllocateDSI( NCSERE,     NBBEM,     NSTVM2,   0)
  Call AllocateDSI( NCSERJP,    NQJPM,    -NSTVM2,   0)
  Call AllocateDSI( NCSERN,     NBBNM,     NSTVM2,   0)
  Call AllocateDSI( NCSERQ,     NQSIJM,    NSTVM2,   0)
  Call AllocateDSI( NCSERS,     NBBSM,     NSTVM2,   0)
  Call AllocateDSI( NCSERW,     NBBWM,     NSTVM2,   0)
  Call AllocateDSI( NSERWQ,     LCM,                  0)
  Call AllocateDSI( NGWSL,      LCM,                  0)
  Call AllocateDSI( NJEL,       NQJPM,                0)
  Call AllocateDSI( NJPMX,      NQJPM,                0)
  Call AllocateDSI( NLOE,       NBBEM,     KCM,       NSTVM2, 0)
  Call AllocateDSI( NLON,       NBBNM,     KCM,       NSTVM2, 0)
  Call AllocateDSI( NLOS,       NBBSM,     KCM,       NSTVM2, 0)
  Call AllocateDSI( NLOW,       NBBWM,     KCM,       NSTVM2, 0)
  Call AllocateDSI( NLRPDRT,    NGLM,         0)
  Call AllocateDSI( NPORTJP,    NQJPM,        0)
                                             
  Call AllocateDSI( NPSERE,     NPBEM,        0)
  Call AllocateDSI( NPSERN,     NPBNM,        0)
  Call AllocateDSI( NPSERS,     NPBSM,        0)
  Call AllocateDSI( NPSERW,     NPBWM,        0)
                                             
  Call AllocateDSI( NPSERE1,    NPBEM,        0)
  Call AllocateDSI( NPSERN1,    NPBNM,        0)
  Call AllocateDSI( NPSERS1,    NPBSM,        0)
  Call AllocateDSI( NPSERW1,    NPBWM,        0)
                                             
  Call AllocateDSI( NQSERJP,    NQJPM,        0)
  Call AllocateDSI( NQSERQ,     NQSIJM,       0)
  Call AllocateDSI( NQSMF,      NQSIJM,       0)
  Call AllocateDSI( NQSMUL,     NQSIJM,       0)
  Call AllocateDSI( NQWRSERJP ,  NQJPM,       0)
  Call AllocateDSI( NTSCRE,     NBBEM,        0)
  Call AllocateDSI( NTSCRN,     NBBNM,        0)
  Call AllocateDSI( NTSCRS,     NBBSM,        0)
  Call AllocateDSI( NTSCRW,     NBBWM,        0)
  Call AllocateDSI( NTSSSS,     MLTMSRM,      0)
  Call AllocateDSI( NTVSFP,     MTVSM,        0)
  Call AllocateDSI( NUDJP,      NQJPM,        0)
  Call AllocateDSI( NUDJPC,     NQJPM,        0)
  Call AllocateDSI( NXYSDAT,    LCM,          0)
  Call AllocateDSI( NZPRJP,     NQJPM,        0)
  Call AllocateDSI( OLDMASK,    LCM,    .false.)
  Call AllocateDSI( P,          LCM,        0.0)
  Call AllocateDSI( P1,         LCM,        0.0)
  Call AllocateDSI( P1DT1,      MLM,        0.0)
  Call AllocateDSI( PATMT,      LCM,        0.0)
  Call AllocateDSI( PCBE,       NPBEM,     MTM,       0.0)
  Call AllocateDSI( PCBN,       NPBNM,     MTM,       0.0)
  Call AllocateDSI( PCBS,       NPBSM,     MTM,       0.0)
  Call AllocateDSI( PCBW,       NPBWM,     MTM,       0.0)
  Call AllocateDSI( PCLSHA,     MLM,       MTM,       0.0)
  Call AllocateDSI( PSERZDF,   -NPSERM,    0.0)       
  Call AllocateDSI( PSERZDS,   -NPSERM,    0.0)       
  Call AllocateDSI( PFAM,       NPFORM,    MTM,       0.0)
  Call AllocateDSI( PFAM1,      NPFORM,    MTM,       0.0)
  Call AllocateDSI( PFAM2,      NPFORM,    MTM,       0.0)
  Call AllocateDSI( PFPH,       NPFORM,    MTM,       0.0)
  Call AllocateDSI( PFPH1,      NPFORM,    MTM,       0.0)
  Call AllocateDSI( PFPH2,      NPFORM,    MTM,       0.0)
  Call AllocateDSI( PHASEE,     MTM,       0.0)
  Call AllocateDSI( PHASEU,     MTM,       0.0)
  Call AllocateDSI( PHASEV,     MTM,       0.0)
  Call AllocateDSI( PHJET,      NQJPM,     0.0)
  Call AllocateDSI( PLSHA,      MLM,       0.0)
  Call AllocateDSI( PMDCH,      NCHANM,    0.0)       
  Call AllocateDSI( PNHYDS,     LCM,       KCM,       0.0)
  Call AllocateDSI( PPH,        LCM,       0.0)       
  Call AllocateDSI( PSBE,       NPBEM,     MTM,       0.0)
  Call AllocateDSI( PSBN,       NPBNM,     MTM,       0.0)
  Call AllocateDSI( PSBS,       NPBSM,     MTM,       0.0)
  Call AllocateDSI( PSBW,       NPBWM,     MTM,       0.0)
  Call AllocateDSI( PSER,       NDPSER,    NPSERM,    0.0)
  Call AllocateDSI( PSERAVG,    NPSERM,    2,         0.0)
  Call AllocateDSI( PSERS,      NDPSER,    NPSERM,    0.0)
  Call AllocateDSI( PSERT,     -NPSERM,    0.0)
  Call AllocateDSI( PSERST,    -NPSERM,    0.0)
  Call AllocateDSI( PSHADE,     LCM,       0.0)
  Call AllocateDSI( PSLSHA,     MLM,       MTM,       0.0)
  Call AllocateDSI( PTLSHA,     MLM,       0.0)
  Call AllocateDSI( PTMP,       LCM,       0.0)
  Call AllocateDSI( QCELLCTR,   LCM,       0.0)
  Call AllocateDSI( QCHANU,     NCHANM,    0.0)
  Call AllocateDSI( QCHANUN,    NCHANM,    0.0)
  Call AllocateDSI( QCHANV,     NCHANM,    0.0)
  Call AllocateDSI( QCHANVN,    NCHANM,    0.0)
  Call AllocateDSI( QCHNULP,    NCHANM,    0.0)
  Call AllocateDSI( QCHNVLP,    NCHANM,    0.0)
  Call AllocateDSI( QCTL,       NDQCLT,    NDQCLT2,   KCM,  NQCTTM,  0.0)
  Call AllocateDSI( QCTLST,     KCM,       NQCTLM,    0.0)
  Call AllocateDSI( QCTLSTO,    KCM,       NQCTLM,    0.0)
  Call AllocateDSI( QCTLT,      KCM,      -NQCTLM,    2,     0.0)
  Call AllocateDSI( QCTLTLP,    KCM,       NQCTLM,    0.0)
  Call AllocateDSI( QCTLTO,     KCM,      -NQCTLM,    0.0)
  Call AllocateDSI( QDNEG,      LCM,       0.0)
  Call AllocateDSI( QDWASTE,    LCM,       0.0)
  Call AllocateDSI( QFACTOR,    NQSIJM,    0.0)
  Call AllocateDSI( QGW,        LCM,       0.0)                              ! *** GROUNDWATER FLUX TERM (M^3/S), 2018-10-24 PMC CHANGED SIGN CONVENTION FOR SEEPAGE +(IN), -(OUT)
  Call AllocateDSI( QJPENT,     KCM,       NQJPM,     0.0)
  Call AllocateDSI( QJPENTT,    NQJPM,     0.0)       
  Call AllocateDSI( QMORPH,     LCM,       0.0)       
  Call AllocateDSI( QQ,         LCM,      -KCM,       0.0)
  Call AllocateDSI( QQ1,        LCM,      -KCM,       0.0)
  Call AllocateDSI( QQ2,        LCM,      -KCM,       0.0)
  Call AllocateDSI( QQSQR,      LCM,      -KCM,       0.0)
  Call AllocateDSI( QQCJP,      NQJPM,     0.0)       
  Call AllocateDSI( QQL,        LCM,      -KCM,       0.0)
  Call AllocateDSI( QQL1,       LCM,      -KCM,       0.0)
  Call AllocateDSI( QQL2,       LCM,      -KCM,       0.0)
  Call AllocateDSI( QQWC,       LCM,       0.0)
  Call AllocateDSI( QQWCR,      LCM,       0.0)
  Call AllocateDSI( QQWV1,      LCM,       0.0)
  Call AllocateDSI( QQWV2,      LCM,       0.0)       
  Call AllocateDSI( QQWV3,      LCM,       0.0)       
  Call AllocateDSI( QRAIN,      LCM,       0.0)       
  Call AllocateDSI( QSERT,      KCM,      -NQSERM,    0.0)
  Call AllocateDSI( QSERCELL,   KCM,      -NQSIJM,    0.0)
  Call AllocateDSI( QSRTLPN,    KCM,       NQSERM,    0.0)
  Call AllocateDSI( QSRTLPP,    KCM,       NQSERM,    0.0)
  Call AllocateDSI( QSS,        KCM,       NQSIJM,    0.0)
  Call AllocateDSI( QSSE,       NQSIJM,    0.0)       
  Call AllocateDSI( QSSDPA,     LCM,       0.0)       
  Call AllocateDSI( QSUM,       LCM,       KCM,       0.0)
  Call AllocateDSI( QSUME,      LCM,       0.0)
  Call AllocateDSI( QSUM1E,     LCM,       0.0)
  Call AllocateDSI( QWATPA,     LCM,       0.0)
  Call AllocateDSI( QWBDTOP,    LCM,       0.0)
  Call AllocateDSI( QWIDTH,     NQSIJM,    0.0)
  Call AllocateDSI( QWRCJP,     NQJPM,     0.0)
  Call AllocateDSI( QWRSER,     NDQWRSR,   NQWRSRM,    0.0)
  Call AllocateDSI( QWRSERT,   -NQWRSRM,   0.0)
  Call AllocateDSI( QWRSERTLP, -NQWRSRM,   0.0)
  Call AllocateDSI( RADBOT,     LCM,       KCM,        0.0)              ! *** SOLAR RADIATION AT THE BOTTOM OF THE LAYER  (W/M2)
  Call AllocateDSI( RADNET,     LCM,       KCM,        0.0)              ! *** NET SOLAR RADIATION AT THE MIDPOINT OF THE LAYER (W/M2)
  Call AllocateDSI( RADTOP,     LCM,      -KCM,        0.0)            ! *** SOLAR RADIATION AT THE TOP OF THE LAYER (W/M2)
  Call AllocateDSI( RADKE,      LCM,       KCM,        0.0)              ! *** EXTINCTION COEFFICIENT AT THE MIDPOINT OF THE LAYER
  Call AllocateDSI( RAINT,      LCM,       0.0)                          ! *** CURRENT RAINFALL PER CELL (M/S)
  Call AllocateDSI( RBPSBL,     LCM,       0.0)        
  Call AllocateDSI( RCX,        LCM,       0.0)        
  Call AllocateDSI( RCY,        LCM,       0.0)        
  Call AllocateDSI( RHAT,       LCM,       0.0)        
  Call AllocateDSI( RHS,        MGM,       0.0)        
  Call AllocateDSI( RMAJ,       MTM,       0.0)        
  Call AllocateDSI( RMIN,       MTM,       0.0)        
  Call AllocateDSI( ROUSE,      LCM,       0.0)        
  Call AllocateDSI( RQSMUL,     NQSIJM,    0.0)        
  Call AllocateDSI( RSOL,       MGM,       0.0)        
  Call AllocateDSI( RSSBCE,     LCM,       0.0)        
  Call AllocateDSI( RSSBCN,     LCM,       0.0)        
  Call AllocateDSI( RSSBCS,     LCM,       0.0)        
  Call AllocateDSI( RSSBCW,     LCM,       0.0)        
  Call AllocateDSI( SAAX,       LCM,       0.0)        
  Call AllocateDSI( SAAY,       LCM,       0.0)        
  Call AllocateDSI( SAL,        LCM,       KCM,        0.0)
  Call AllocateDSI( SAL1,       LCM,       KCM,        0.0)
  Call AllocateDSI( SALINIT,    LCM,       KCM,        0.0)
  Call AllocateDSI( SBX,        LCM,       0.0)        
  Call AllocateDSI( SBXO,       LCM,       0.0)        
  Call AllocateDSI( SBY,        LCM,       0.0)        
  Call AllocateDSI( SBYO,       LCM,       0.0)        
  Call AllocateDSI( SCAX,       LCM,       0.0)        
  Call AllocateDSI( SCAY,       LCM,       0.0)        
  Call AllocateDSI( SCB,        LCM,       0.0)        
  Call AllocateDSI( SCLSHA,     MTM,       MTM,        0.0)
  Call AllocateDSI( SDX,        LCM,       0.0)        
  Call AllocateDSI( SDY,        LCM,       0.0)        
                                                      
  Call AllocateDSI( SFL,        LCM,       KCM,        0.0)
  Call AllocateDSI( SFL2,       LCM,       KCM,        0.0)
  Call AllocateDSI( SFLINIT,    LCM,       KCM,        0.0)
  Call AllocateDSI( SFLSBOT,    LCM,       0.0)
                                         
  Call AllocateDSI( SIGPHIA,    LCM,       0.0)
  Call AllocateDSI( SNAPSHOTS,  5000,      0.0)  ! *** PMC - Hardwired for now
                                         
  Call AllocateDSI( SOLSWRT,   LCM,        0.0)
  Call AllocateDSI( SPB,       LCM,        0.0)
  Call AllocateDSI( SPBE1,     NPBEM,      0.0)
  Call AllocateDSI( SPBE2,     NPBEM,      0.0)
  Call AllocateDSI( SPBN1,     NPBNM,      0.0)
  Call AllocateDSI( SPBN2,     NPBNM,      0.0)
  Call AllocateDSI( SPBS1,     NPBSM,      0.0)
  Call AllocateDSI( SPBS2,     NPBSM,      0.0)
  Call AllocateDSI( SPBW1,     NPBWM,      0.0)
  Call AllocateDSI( SPBW2,     NPBWM,      0.0)
  Call AllocateDSI( SPFAM0,    NPFORM,     MTM,       0.0)
  Call AllocateDSI( SPFAM1,    NPFORM,     MTM,       0.0)
  Call AllocateDSI( SPFAM2,    NPFORM,     MTM,       0.0)
  Call AllocateDSI( SSLSHA,    MTM,        MTM,       0.0)
  Call AllocateDSI( SSSIN,     MTM,        0.0)
  Call AllocateDSI( SSSIN1,    MTM,        0.0)
  Call AllocateDSI( SSSS,      MTM,        0.0)
  Call AllocateDSI( STBX,      LCM,        0.0)
  Call AllocateDSI( STBXO,     LCM,        0.0)
  Call AllocateDSI( STBY,      LCM,        0.0)
  Call AllocateDSI( STBYO,     LCM,        0.0)
  Call AllocateDSI( STCAP,     LCM,        0.0)
  Call AllocateDSI( STCUV,     LCM,        0.0)
  Call AllocateDSI( STLSHA,    MTM,        0.0)
  Call AllocateDSI( SUB,       LCM,        0.0)
  Call AllocateDSI( SUBO,      LCM,        0.0)
  Call AllocateDSI( UMASK,    -LCM,          0)
  Call AllocateDSI( VMASK,    -LCM,          0)
  Call AllocateDSI( SVB,       LCM,        0.0)
  Call AllocateDSI( SVBO,      LCM,        0.0)
  Call AllocateDSI( SVPAT,     LCM,        0.0)
  Call AllocateDSI( SVPW,      LCM,        0.0)
  Call AllocateDSI( SWB,       LCM,        0.0)
  Call AllocateDSI( TACSER,    NCSERM,     NSTVM2,    0.0)
  Call AllocateDSI( TAGWSER,   NGWSERM,    0.0)
  Call AllocateDSI( TAPSER,    NPSERM,     0.0)
  Call AllocateDSI( TAQSER,    NQSERM,     0.0)
  Call AllocateDSI( TAQWRSR,   NQWRSRM,    0.0)
  Call AllocateDSI( TATMT,     LCM,        0.0)
  Call AllocateDSI( TAUB,      LCM,        0.0)                   ! *** Density normalized bed shear stress (m2/s2)
  Call AllocateDSI( TAVEGSER,  NVEGSERM,   0.0)
  Call AllocateDSI( TBX,       LCM,        0.0)
  Call AllocateDSI( TBX1,      LCM,        0.0)
  Call AllocateDSI( TBY,       LCM,        0.0)
  Call AllocateDSI( TBY1,      LCM,        0.0)
  Call AllocateDSI( TCCSER,    NCSERM,     NSTVM,     0.0)
  Call AllocateDSI( TCGWSER,   NGWSERM,    0.0)
  Call AllocateDSI( TCP,       MTM,        0.0)
  Call AllocateDSI( TCPSER,    NPSERM,     0.0)
  Call AllocateDSI( TCQSER,    NQSERM,     0.0)
  Call AllocateDSI( TCQWRSR,   NQWRSRM,    0.0)
  Call AllocateDSI( TCVEGSER,  NVEGSERM,   0.0)
  Call AllocateDSI( TDEWT,     LCM,        0.0)
  Call AllocateDSI( TEM,       LCM,        KCM,       0.0)
  Call AllocateDSI( TEM1,      LCM,        KCM,       0.0)
  Call AllocateDSI( TEMB,      LCM,        0.0)
  Call AllocateDSI( TEMB1,     LCM,        0.0)
  Call AllocateDSI( TEMINIT,   LCM,        KCM,       0.0)
  Call AllocateDSI( TGWSER,    NDGWSER,    NGWSERM,   0.0)
  Call AllocateDSI( THJET,     NQJPM,      0.0)
  Call AllocateDSI( TMP3D,     KCM,        0.0)
                             
  Call AllocateDSI( TPCOORDE,  NPBEM,      0.0)
  Call AllocateDSI( TPCOORDN,  NPBNM,      0.0)
  Call AllocateDSI( TPCOORDS,  NPBSM,      0.0)
  Call AllocateDSI( TPCOORDW,  NPBWM,      0.0)
                             
  Call AllocateDSI( TPSER,     NDPSER,     NPSERM,    0.0)
  Call AllocateDSI( TQWRSER,   NDQWRSR,    NQWRSRM,   0.0)
  !ALLOCATE(TSSRD(NDASER, 0. 0)
  Call AllocateDSI( TSSTOP,    MTSSTSPM,   NTSSTSPM,  0.0)
  Call AllocateDSI( TSSTRT,    MTSSTSPM,   NTSSTSPM,  0.0)
  Call AllocateDSI( TSX,       LCM,        0.0)
  Call AllocateDSI( TSX1,      LCM,        0.0)
  Call AllocateDSI( TSY,       LCM,        0.0)
  Call AllocateDSI( TSY1,      LCM,        0.0)
  Call AllocateDSI( TVAR1E,    LCM,        KCM,       0.0)
  Call AllocateDSI( TVAR1N,    LCM,        KCM,       0.0)
  Call AllocateDSI( TVAR1S,    LCM,        KCM,       0.0)
  Call AllocateDSI( TVAR1W,    LCM,        KCM,       0.0)
  Call AllocateDSI( TVAR2C,    LCM,       -KCM,       0.0)
  Call AllocateDSI( TVAR2E,    LCM,        KCM,       0.0)
  Call AllocateDSI( TVAR2N,    LCM,        KCM,       0.0)
  Call AllocateDSI( TVAR2S,    LCM,        KCM,       0.0)
  Call AllocateDSI( TVAR2W,    LCM,        KCM,       0.0)
  Call AllocateDSI( TVAR3C,    LCM,        0.0)
  Call AllocateDSI( TVAR3E,    LCM,        0.0)
  Call AllocateDSI( TVAR3N,    LCM,        0.0)
  Call AllocateDSI( TVAR3S,    LCM,        0.0)
  Call AllocateDSI( TVAR3W,    LCM,        0.0)
  Call AllocateDSI( TVEGSER,   NDVEGSER,   NVEGSERM,  0.0)
  Call AllocateDSI( TWATER,    LCM,        0.0)                      ! *** For outputing water temperature to tecplot.  Otherwise can use for temporary debugging
  Call AllocateDSI( U,         LCM,        KCM,       0.0)
  Call AllocateDSI( U0,        KCM,        MLM,       0.0)
  Call AllocateDSI( U1,        LCM,        KCM,       0.0)
  Call AllocateDSI( U1V,       LCM,        0.0)      
  Call AllocateDSI( U2,        LCM,        KCM,       0.0)
  Call AllocateDSI( UCELLCTR,  LCM,        0.0)      
  Call AllocateDSI( UCLSHA,    KCM,        MLM,       MTM,  0.0)
  Call AllocateDSI( UCOS,      MTM,        0.0)      
  Call AllocateDSI( UE0,       MLM,        0.0)      
  Call AllocateDSI( UE1DT1,    MLM,        0.0)      
  Call AllocateDSI( UECLSHA,   MLM,        MTM,       0.0)
  Call AllocateDSI( UELSHA,    MLM,        0.0)      
  Call AllocateDSI( UESLSHA,   MLM,        MTM,       0.0)
  Call AllocateDSI( UETLSHA,   MLM,        0.0)      
  Call AllocateDSI( UHDY1E,    LCM,        0.0)      
  Call AllocateDSI( UHDY2E,    LCM,        0.0)      
  Call AllocateDSI( UHDYE,     LCM,        0.0)      
  Call AllocateDSI( UHDYEK,    LCM,        KCM,       0.0)
  Call AllocateDSI( UHDY1EK,   LCM,        KCM,       0.0)
  Call AllocateDSI( UHDY2EK,   LCM,        KCM,       0.0)
  Call AllocateDSI( UHE,       LCM,        0.0)      
  Call AllocateDSI( USIN,      MTM,        0.0)      
  Call AllocateDSI( USLSHA,    KCM,        MLM,       MTM,  0.0)
  Call AllocateDSI( USTAR,     LCM,        0.0)      
  Call AllocateDSI( USTARSED,  LCM,        0.0)      
  Call AllocateDSI( USTARSND,  LCM,        0.0)      
  Call AllocateDSI( UUU,       LCM,        KCM,       0.0)
  Call AllocateDSI( UV,        LCM,        0.0)      
  Call AllocateDSI( UWVSQ,     LCM,        0.0)      
  Call AllocateDSI( V,         LCM,        KCM,       0.0)
  Call AllocateDSI( V0,        KCM,        MLM,       0.0)
  Call AllocateDSI( V1,        LCM,        KCM,       0.0)
  Call AllocateDSI( V1U,       LCM,        0.0)      
  Call AllocateDSI( V2,       LCM,         KCM,       0.0)
  Call AllocateDSI( VCELLCTR, LCM,         0.0)      
  Call AllocateDSI( VCLSHA,   KCM,         MLM,       MTM,   0.0)
  Call AllocateDSI( VCOS,     MTM,         0.0)      
  Call AllocateDSI( VDWASTE,  LCM,         0.0)      
  Call AllocateDSI( VE0,      MLM,         0.0)      
  Call AllocateDSI( VE1DT1,   MLM,         0.0)      
  Call AllocateDSI( VECLSHA,  MLM,         MTM,       0.0)
  Call AllocateDSI( VEGK,     LCM,         0.0)      
  Call AllocateDSI( VEGSERB,  NDVEGSER,    NVEGSERM,  0.0)
  Call AllocateDSI( VEGSERBT, NVEGSERM,    0.0)
  Call AllocateDSI( VEGSERH,  NDVEGSER,    NVEGSERM,  0.0)
  Call AllocateDSI( VEGSERHT, NVEGSERM,    0.0)       
  Call AllocateDSI( VEGSERR,  NDVEGSER,    NVEGSERM,  0.0)
  Call AllocateDSI( VEGSERRT, NVEGSERM,    0.0)
  Call AllocateDSI( VELSHA,   MLM,         0.0)
  Call AllocateDSI( VESLSHA,  MLM,         MTM,       0.0)
  Call AllocateDSI( VETLSHA,  MLM,         0.0)
  Call AllocateDSI( VHDX1E,   LCM,         0.0)
  Call AllocateDSI( VHDX2E,   LCM,         0.0)
  Call AllocateDSI( VHDXE,    LCM,         0.0)
  Call AllocateDSI( VHDXEK,   LCM,         KCM,       0.0)
  Call AllocateDSI( VHDX1EK,  LCM,         KCM,       0.0)
  Call AllocateDSI( VHDX2EK,  LCM,         KCM,       0.0)
  Call AllocateDSI( VHE,      LCM,         0.0)
  Call AllocateDSI( VOLPERC,  LCM,         0.0)
  Call AllocateDSI( VOLSEL,   LCM,         0.0)
  Call AllocateDSI( VPAT,     LCM,         0.0)
  Call AllocateDSI( VSIN,     MTM,         0.0)
  Call AllocateDSI( VU,       LCM,         0.0)
  Call AllocateDSI( VVV,      LCM,         KCM,       0.0)
  Call AllocateDSI( W,        LCM,        -KCM,       0.0)
  Call AllocateDSI( W1,       LCM,        -KCM,       0.0)
  Call AllocateDSI( W2,       LCM,        -KCM,       0.0)
  Call AllocateDSI( WACCWE,   LCM,         0.0)
  Call AllocateDSI( WCOREST,  LCM,         0.0)
  Call AllocateDSI( WCORWST,  LCM,         0.0)
  Call AllocateDSI( WCORNTH,  LCM,         0.0)
  Call AllocateDSI( WCORSTH,  LCM,         0.0)
  Call AllocateDSI( WINDCD10, LCM,         0.0)              ! *** WIND DRAG COEFFICIENT FOR EACH CELL (NO DIM)
  Call AllocateDSI( WINDST,   LCM,         0.0)              ! *** WIND SPEED AT 2 METERS FOR EACH CELL (M/S)
  Call AllocateDSI( WINDSTKA, LCM,         0.0)              ! *** WIND SHELTERING COEFFICIENT
  Call AllocateDSI( WINDSTKA_SAVE,         LCM,       0.0)
  Call AllocateDSI( WKQ,      KCM,         0.0)       
  Call AllocateDSI( WNDVELE,  LCM,         0.0)       
  Call AllocateDSI( WNDVELN,  LCM,         0.0)       
  Call AllocateDSI( WTCI,     KCM,         2,         0.0)
  Call AllocateDSI( WVDTKEM,  KCM,         0.0)       
  Call AllocateDSI( WVDTKEP,  KCM,         0.0)       
  Call AllocateDSI( WVENEP,   LCM,         0.0)       
  Call AllocateDSI( WVHUU,    LCM,         KCM,       0.0)
  Call AllocateDSI( WVHUV,    LCM,         KCM,       0.0)
  Call AllocateDSI( WVHVV,    LCM,         KCM,       0.0)
  Call AllocateDSI( WVKHC,    LCM,         0.0)       
  Call AllocateDSI( WVKHU,    LCM,         0.0)       
  Call AllocateDSI( WVKHV,    LCM,         0.0)       
  Call AllocateDSI( WVPP,     LCM,         KCM,       0.0)
  Call AllocateDSI( WVPT,     LCM,        -KCM,       0.0)
  Call AllocateDSI( WVPU,     LCM,         KCM,       0.0)
  Call AllocateDSI( WVPV,     LCM,         KCM,       0.0)
  Call AllocateDSI( WVTMP1,   LCM,         0.0)
  Call AllocateDSI( WVTMP2,   LCM,         0.0)
  Call AllocateDSI( WVTMP3,   LCM,         0.0)
  Call AllocateDSI( WVTMP4,   LCM,         0.0)

  Call AllocateDSI( WWW,      LCM,        -KCM,       0.0)
  Call AllocateDSI( XJETL,    NQJPM,       0.0)       
  Call AllocateDSI( YJETL,    NQJPM,       0.0)       
                                                     
  Call AllocateDSI( Z,        LCM,         -KCM,      0.0)
  Call AllocateDSI( ZBR,      LCM,         0.0)
  Call AllocateDSI( ZBRE,     LCM,         0.0)
  Call AllocateDSI( ZEQ,      LCM,         0.0)
  Call AllocateDSI( ZEQD,     LCM,         0.0)
  Call AllocateDSI( ZEQDI,    LCM,         0.0)
  Call AllocateDSI( ZEQI,     LCM,         0.0)
  Call AllocateDSI( ZETATOP,  LCM,         0.0)
  Call AllocateDSI( ZJET,     NQJPM,       0.0)
  Call AllocateDSI( ZP,       -KPCM,       0.0)
  Call AllocateDSI( ZZ,       LCM,        -KCM,       0.0)
  Call AllocateDSI( ZZC,      -KCM,        LCM,       0.0)
  Call AllocateDSI( ZZP,      KPCM,        0.0)

  ! *** NEXT SECTION ALLOCATES USAGE DEPENDENT VARIABLES
  !IF( ISDRY > 0 ) ALLOCATE(TIMEDRY(LCM, 0.0)

  IF( ISINWV == 1 .OR. ISNEGH > 0 )THEN
    Call AllocateDSI( CFLCAC,   LCM,       KCM,       0.0)
    Call AllocateDSI( CFLUUU,   LCM,       KCM,       0.0)
    Call AllocateDSI( CFLVVV,   LCM,       KCM,       0.0)
    Call AllocateDSI( CFLWWW,   LCM,      -KCM,       0.0)
  ENDIF

  IF( ISVHEAT > 0 )THEN
    Call AllocateDSI( LSVHTWINDE, LCM, .false.)
    Call AllocateDSI( LSVHTWINDC, LCM, .false.)
    Call AllocateDSI( SVREVC,     LCM,     0.0)
    Call AllocateDSI( SVRCHC,     LCM,     0.0)
  ENDIF
  Call AllocateDSI( SVKEBACK, LCM, 0.0)

  IF( ISDISP > 0 )THEN
    Call AllocateDSI( BDISP,    KCM,  KCM,  LCM,  0.0)
    Call AllocateDSI( CUDISPT,  KCM,  LCM,  0.0)
    Call AllocateDSI( CVDISPT,  KCM,  LCM,  0.0)
    Call AllocateDSI( DYXTCA,   LCM,  0.0)  
    Call AllocateDSI( DYYTCA,   LCM,  0.0)  
    Call AllocateDSI( FVDISP,   KCM,  LCM,  0.0)
  ENDIF

  IF( ISHDMF >= 1 )THEN
    Call AllocateDSI( FMDUX,    LCM,  KCM,  0.0)
    Call AllocateDSI( FMDUY,    LCM,  KCM,  0.0)
    Call AllocateDSI( FMDVX,    LCM,  KCM,  0.0)
    Call AllocateDSI( FMDVY,    LCM,  KCM,  0.0)
    IF( IS2TIM == 0 ) Call AllocateDSI( H1C, LCM, 0.0)
  ENDIF

  IF( ISVEG > 0 )THEN
    Call AllocateDSI( FXVEG,     LCM,      KCM,   0.0)
    Call AllocateDSI( FXVEGE,    LCM,      0.0)   
    Call AllocateDSI( FYVEG,     LCM,      KCM,   0.0)
    Call AllocateDSI( FYVEGE,    LCM,      0.0)
    Call AllocateDSI( LVEG,      LCM,  .false.)
    Call AllocateDSI( NVEGSERV, -NVEGTPM,    0)
    Call AllocateDSI( ALPVEG,   -NVEGTPM,  0.0)
    Call AllocateDSI( BDLPSQ,   -NVEGTPM,  0.0)
    !ALLOCATE(BETVEG(-NVEGTPM, 0.0)       
    Call AllocateDSI( BPVEG,    -NVEGTPM,  0.0)
    !ALLOCATE(GAMVEG(-NVEGTPM, 0.0)       
    Call AllocateDSI( HPVEG,    -NVEGTPM,  0.0)
    !ALLOCATE(PVEGX(-NVEGTPM, 0.0)        
    !ALLOCATE(PVEGY(-NVEGTPM, 0.0)        
    Call AllocateDSI( PVEGZ,    -NVEGTPM,  0.0)
    Call AllocateDSI( RDLPSQ,   -NVEGTPM,  0.0)
    Call AllocateDSI( SCVEG,    -NVEGTPM,  0.0)
  ENDIF

  IF( ISWAVE > 0 )THEN
    Call AllocateDSI( FXWAVE,   LCM,  KCM, 0.0)
    Call AllocateDSI( FYWAVE,   LCM,  KCM, 0.0)
    DO L=1, LCM
      Call AllocateDSI( WV(L).DISSIPA, KCM, 0.0)
    ENDDO
  ENDIF

  ! *** FOODCHAIN MODELLING OPTIONS
  IF( ISTPOCB == 4 )THEN
    Call AllocateDSI( PFPOCB,   LCM, KBM, 0.0)
    Call AllocateDSI( FPOCB,    LCM, KBM, 0.0)
  ELSE
    Call AllocateDSI( PFPOCB,   1, 1, 0.0)
    Call AllocateDSI( FPOCB,    1, 1, 0.0)
  ENDIF

  ! ** TOXIC TRANSPORT VARIABLES
  Call AllocateDSI( ISDIFBW,         NTXM,   0)
  Call AllocateDSI( ISPMXZ,          NTXM,   0)
  Call AllocateDSI( ISTOC,           NTXM,   0)
  Call AllocateDSI( ISTOXR,          NTXM,   0)
  Call AllocateDSI( ITOXBU,          NTXM,   0)
  Call AllocateDSI( ITOXKIN,         10,     NTXM,   0)
  Call AllocateDSI( ITOXWU,          NTXM,   0)
  Call AllocateDSI( ITXBDUT,         NTXM,   0)
  Call AllocateDSI( ITXINT,          NTXM,   0)
  Call AllocateDSI( ITXPARW,         NSTM2,  NTXM,   0)
  Call AllocateDSI( ITXPARWC,        2,      NTXM,   0)
                                            
  Call AllocateDSI( CONPARW,         NSTM2,  NTXM,  0.0)
  Call AllocateDSI( CONPARWC,        2,      NTXM,  0.0)
  Call AllocateDSI( DIFTOX,          NTXM,   0.0)
  Call AllocateDSI( DIFTOXS,         NTXM,   0.0)
  Call AllocateDSI( DPDIFTOX,        NTXM,   0.0)
  Call AllocateDSI( FPOCBST,         NSTM2,  NTXM, 0.0)
  Call AllocateDSI( FPOCWST,         NSTM2,  NTXM, 0.0)
  Call AllocateDSI( PDIFTOX,         NTXM,   0.0)
  Call AllocateDSI( RKTOXP,          NTXM,   0.0)
  Call AllocateDSI( SKTOXP,          NTXM,   0.0)
  Call AllocateDSI( TOXINTB,         NTXM,   0.0)
  Call AllocateDSI( TOXINTW,         NTXM,   0.0)
  Call AllocateDSI( TOX_BIO_KB,      NTXM,   0.0)
  Call AllocateDSI( TOX_BIO_KW,      NTXM,   0.0)
  Call AllocateDSI( TOX_BIO_MXD,     NTXM,   0.0)
  Call AllocateDSI( TOX_BIO_Q10B,    NTXM,   0.0)
  Call AllocateDSI( TOX_BIO_Q10W,    NTXM,   0.0)
  Call AllocateDSI( TOX_BIO_TB,      NTXM,   0.0)
  Call AllocateDSI( TOX_BIO_TW,      NTXM,   0.0)
  Call AllocateDSI( TOX_BLK_KB,      NTXM,   0.0)
  Call AllocateDSI( TOX_BLK_KW,      NTXM,   0.0)
  Call AllocateDSI( TOX_BLK_MXD,     NTXM,   0.0)
  Call AllocateDSI( TOX_ADJ,         NTXM,   0.0)
  Call AllocateDSI( TOX_ATM,         NTXM,   0.0)
  Call AllocateDSI( TOX_HE,          NTXM,   0.0)
  Call AllocateDSI( TOX_MW,          NTXM,   0.0)
  Call AllocateDSI( TOX_KV_TCOEFF,   NTXM,   0.0)
                                    
  Call AllocateDSI( TOXPARB,         LCM,    NSTM2,  NTXM,    0.0)
  Call AllocateDSI( TOXPARBC,        2,      NTXM,    0.0)
  Call AllocateDSI( TOXPARW,         LCM,    NSTM2,  NTXM,    0.0)
  Call AllocateDSI( TOXPARWC,        2,      NTXM,    0.0)
  Call AllocateDSI( TOX,             LCM,    KCM,     NTXM,  0.0)
  Call AllocateDSI( TOX1,            LCM,    KCM,     NTXM,  0.0)

  IF( ISTRAN(5) >= 1 .OR. ISBAL > 0 .OR. NTOX > 0 )THEN
    Call AllocateDSI( NSP2,          NTXM,   0)
    Call AllocateDSI( RTOXERE2T,     NTXM,   0.0)
    Call AllocateDSI( RTOXERE2TB,    NTXM,   0.0)
    Call AllocateDSI( RTOXERE2TW,    NTXM,   0.0)
    Call AllocateDSI( RTOXERO2T,     NTXM,   0.0)
    Call AllocateDSI( RTOXERO2TB,    NTXM,   0.0)
    Call AllocateDSI( RTOXERO2TW,    NTXM,   0.0)
    Call AllocateDSI( STPOCW,        LCM,    KCM,     0.0)
    Call AllocateDSI( TADFLUX,       LCM,    NTXM,    0.0)
    Call AllocateDSI( TADFLUX2T,     NTXM,   0.0)     
    Call AllocateDSI( TOXATM,        LCM,    NTXM,    0.0)
    Call AllocateDSI( TOXB,          LCM,    KBM,     NTXM,  0.0)
    Call AllocateDSI( TOXB1,         LCM,    KBM,     NTXM,  0.0)
    Call AllocateDSI( TOXBEG2T,      NTXM,   0.0)
    Call AllocateDSI( TOXBEG2TB,     NTXM,   0.0)
    Call AllocateDSI( TOXBEG2TW,     NTXM,   0.0)
    Call AllocateDSI( TOXBINIT,      LCM,    KBM, NTXM, 0.0)
    Call AllocateDSI( TOXBLB,        NTXM,   0.0)
    Call AllocateDSI( TOXBLB2T,      NTXM,   0.0)
    Call AllocateDSI( TOXBMO2T,      NTXM,   0.0)
    Call AllocateDSI( TOXBMO2TB,     NTXM,   0.0)
    Call AllocateDSI( TOXBMO2TW,     NTXM,   0.0)
    Call AllocateDSI( TOXBS,         LCM,    KBM, NTXM, 0.0)
    Call AllocateDSI( TOXCDFB,       LCM,    KBM, NTXM, 0.0)
    Call AllocateDSI( TOXCDFW,       LCM,    KCM, NTXM, 0.0)
    Call AllocateDSI( TOXEND2T,      NTXM,   0.0)
    Call AllocateDSI( TOXEND2TB,     NTXM,   0.0)
    Call AllocateDSI( TOXEND2TW,     NTXM,   0.0)
    Call AllocateDSI( TOXERE2T,      NTXM,   0.0)
    Call AllocateDSI( TOXERE2TB,     NTXM,   0.0)
    Call AllocateDSI( TOXERE2TW,     NTXM,   0.0)
    Call AllocateDSI( TOXERO2T,      NTXM,   0.0)
    Call AllocateDSI( TOXERO2TB,     NTXM,   0.0)
    Call AllocateDSI( TOXERO2TW,     NTXM,   0.0)
    Call AllocateDSI( TOXERR2T,      NTXM,   0.0)
    Call AllocateDSI( TOXERR2TB,     NTXM,   0.0)
    Call AllocateDSI( TOXERR2TW,     NTXM,   0.0)
    Call AllocateDSI( TOXF,          LCM,   -KCM,     NTXM,  0.0)    ! *** TOXIC CONTAMINANT SETTLING AND BED EXCHANGE FLUX  (G/M2/S)
    Call AllocateDSI( TOXFB,         LCM,    NTXM,    0.0)           ! *** TOXIC CONTAMINANT EROSIONAL FLUX AT THE BED/WATER INTERFACE  (G/M2/S)
    Call AllocateDSI( TOXFBL,        LCM,    NTXM,    0.0)           ! *** TOXIC CONTAMINANT FLUX AT THE BED/WATER INTERFACE DUE TO BEDLOAD   (G/M2/S)
    Call AllocateDSI( TOXFBL2T,      NTXM,   0.0)
    Call AllocateDSI( TOXFBLT,       NTXM,   0.0)
    Call AllocateDSI( TOXFBEBKB,     LCM,    NTXM,    0.0)
    Call AllocateDSI( TOXFBECHB,     LCM,    NTXM,    0.0)
    Call AllocateDSI( TOXFBECHW,     LCM,    NTXM,    0.0)
    Call AllocateDSI( TOXFDFB,       LCM,    KBM,     NTXM, 0.0)
    Call AllocateDSI( TOXFDFW,       LCM,    KCM,     NTXM, 0.0)
    Call AllocateDSI( TOXFLUXB2T,    NTXM,   0.0)    
    Call AllocateDSI( TOXFLUXW2T,    NTXM,   0.0)    
    Call AllocateDSI( TOXINIT,       LCM,    KCM,     NTXM, 0.0)
    Call AllocateDSI( TOXOUT2T,      NTXM,   0.0)    
    Call AllocateDSI( TOXOUT2TB,     NTXM,   0.0)    
    Call AllocateDSI( TOXOUT2TW,     NTXM,   0.0)    
    Call AllocateDSI( TOXPFB,        LCM,    KBM,     NSTM2+2, NTXM,  0.0)
    Call AllocateDSI( TOXPFTB,       LCM,    KBM,     NTXM,    0.0)  
    Call AllocateDSI( TOXPFTW,       LCM,    KCM,     NTXM,    0.0)  
    Call AllocateDSI( TOXPFW,        LCM,    KCM,     NSTM2+2, NTXM,  0.0)
    Call AllocateDSI( TOXS,          LCM,    KCM,     NTXM,    0.0)
    Call AllocateDSI( TOXTMP,        LCM,   -KBM+1 ,  0.0)
  ENDIF   ! *** END OF TOXIC VARIABLE DECLARATIONS

  ! ** SED VARIABLES
  Call AllocateDSI( SED,      LCM,  KCM,  NSCM2,  0.0)
  Call AllocateDSI( SED1,     LCM,  KCM,  NSCM2,  0.0)
  Call AllocateDSI( SDF,      LCM,  KCM,   NSCM,  0.0)
  IF( ISTRAN(6) >= 1 .OR. ISBAL > 0 .OR. NSED > 0 )THEN
    Call AllocateDSI( SED3DMAX,      NSCM2,   0.0)
    Call AllocateDSI( SED3DMIN,      NSCM2,   0.0)
    Call AllocateDSI( SEDBA,         LCM,     NSCM,   0.0)
    Call AllocateDSI( SEDBEG2T,      NSCM,    0.0)
    Call AllocateDSI( SEDBEG2TB,     NSCM,    0.0)
    Call AllocateDSI( SEDBEG2TW,     NSCM,    0.0)
    Call AllocateDSI( SEDBINIT,      LCM,     KBM,    NSCM, 0.0)
    Call AllocateDSI( SEDBMO2T,      NSCM,    0.0)
    Call AllocateDSI( SEDBMO2TB,     NSCM,    0.0)
    Call AllocateDSI( SEDBMO2TW,     NSCM,    0.0)
    Call AllocateDSI( SEDEND2T,      NSCM2,   0.0)
    Call AllocateDSI( SEDEND2TB,     NSCM2,   0.0)
    Call AllocateDSI( SEDEND2TW,     NSCM2,   0.0)
    Call AllocateDSI( SEDERE2T,      NSCM2,   0.0)
    Call AllocateDSI( SEDERE2TB,     NSCM2,   0.0)
    Call AllocateDSI( SEDERE2TW,     NSCM2,   0.0)
    Call AllocateDSI( SEDERO2T,      NSCM2,   0.0)
    Call AllocateDSI( SEDERO2TB,     NSCM2,   0.0)
    Call AllocateDSI( SEDERO2TW,     NSCM2,   0.0)
    Call AllocateDSI( SEDERR2T,      NSCM2,   0.0)
    Call AllocateDSI( SEDERR2TB,     NSCM2,   0.0)
    Call AllocateDSI( SEDERR2TW,     NSCM2,   0.0)
    Call AllocateDSI( SEDF,          LCM,    -KCM,    NSCM2, 0.0)      ! *** VERTICAL SED FLUX ACROSS CELL LAYER FACES (G/M2/S)
    Call AllocateDSI( SEDINIT,       LCM,     KCM,    NSCM2, 0.0)
    Call AllocateDSI( SEDOUT2T,      NSCM2,   0.0)
    Call AllocateDSI( SEDOUT2TB,     NSCM2,   0.0)
    Call AllocateDSI( SEDOUT2TW,     NSCM2,   0.0)
    Call AllocateDSI( SEDS,          LCM,     KCM,    NSCM2, 0.0)
    Call AllocateDSI( SEDFLUX2T,     NSCM2,   0.0)      
  ENDIF   ! *** END OF SED VARIABLE DECLARATIONS

  ! ** SND VARIABLES
  Call AllocateDSI( SND,      LCM, KCM, NSNM, 0.0)
  Call AllocateDSI( SND1,     LCM, KCM, NSNM, 0.0)
  IF( NSND > 0 )THEN
    Call AllocateDSI( SBDLDA,        NSNM,    0.0)
    Call AllocateDSI( SBDLDB,        NSNM,    0.0)
    Call AllocateDSI( SBDLDG1,       NSNM,    0.0)
    Call AllocateDSI( SBDLDG2,       NSNM,    0.0)
    Call AllocateDSI( SBDLDG3,       NSNM,    0.0)
    Call AllocateDSI( SBDLDG4,       NSNM,    0.0)
    Call AllocateDSI( SBDLDP,        NSNM,    0.0)
  ENDIF
  IF( ISTRAN(7) >= 1 .OR. ISBAL > 0 )THEN
    Call AllocateDSI( SBLOUT2T,      NSNM,    0.0)
    Call AllocateDSI( SBLOUT2TB,     NSNM,    0.0)
    Call AllocateDSI( SBLOUT2TW,     NSNM,    0.0)
    Call AllocateDSI( SND3DMAX,      NSNM,    0.0)
    Call AllocateDSI( SND3DMIN,      NSNM,    0.0)
    Call AllocateDSI( SNDBA,         LCM,     NSNM,   0.0)
    Call AllocateDSI( SNDBA1,        LCM,     NSNM,   0.0)
    Call AllocateDSI( SNDBAT,        LCM,     0.0)    
    Call AllocateDSI( SNDBEG2T,      NSNM,    0.0)    
    Call AllocateDSI( SNDBEG2TB,     NSNM,    0.0)    
    Call AllocateDSI( SNDBEG2TW,     NSNM,    0.0)    
    Call AllocateDSI( SNDBINIT,      LCM,     KBM,    NSNM,  0.0)
    Call AllocateDSI( SNDBMO2T,      NSNM,    0.0)          
    Call AllocateDSI( SNDBMO2TB,     NSNM,    0.0)          
    Call AllocateDSI( SNDBMO2TW,     NSNM,    0.0)          
    Call AllocateDSI( SNDBS,         LCM,     KBM,    NSNM,  0.0)
    Call AllocateDSI( SNDEND2T,      NSNM,    0.0)          
    Call AllocateDSI( SNDEND2TB,     NSNM,    0.0)          
    Call AllocateDSI( SNDEND2TW,     NSNM,    0.0)          
    Call AllocateDSI( SNDEQ,         LCM,     0.0)          
    Call AllocateDSI( SNDEQSAV,      LCM,     NSNM,   0.0)  
    Call AllocateDSI( SNDEQB,        LCM,     0.0)          
    Call AllocateDSI( SNDERE2T,      NSNM,    0.0)          
    Call AllocateDSI( SNDERE2TB,     NSNM,    0.0)          
    Call AllocateDSI( SNDERE2TW,     NSNM,    0.0)          
    Call AllocateDSI( SNDERO2T,      NSNM,    0.0)          
    Call AllocateDSI( SNDERO2TB,     NSNM,    0.0)          
    Call AllocateDSI( SNDERO2TW,     NSNM,    0.0)          
    Call AllocateDSI( SNDERR2T,      NSNM,    0.0)          
    Call AllocateDSI( SNDERR2TB,     NSNM,    0.0)          
    Call AllocateDSI( SNDERR2TW,     NSNM,    0.0)          
    Call AllocateDSI( SNDF,          LCM,    -KCM,    NSNM,  0.0)      ! *** VERTICAL SND FLUX ACROSS CELL LAYER FACES (G/M2/S)
    Call AllocateDSI( SNDFBL,        LCM,     NSNM,   0.0)             ! *** BED/WATER INTERFACE SND FLUX DUE TO BEDLOAD (G/M2/S)
    Call AllocateDSI( SNDFBL2T,      NSNM,    0.0)          
    Call AllocateDSI( SNDFLUX2T,     NSNM,    0.0)          
    Call AllocateDSI( SNDINIT,       LCM,     KCM,    NSNM,  0.0)
    Call AllocateDSI( SNDOUT2T,      NSNM,    0.0)    
    Call AllocateDSI( SNDOUT2TB,     NSNM,    0.0)    
    Call AllocateDSI( SNDOUT2TW,     NSNM,    0.0)    
    Call AllocateDSI( SNDS,          LCM,     KCM,    NSNM,  0.0)
  ENDIF   ! *** END OF SND VARIABLE DECLARATIONS

  ! *** EITHER SED OR SND
  Call AllocateDSI( IBLTAUC,       NSCM2,    0)
  Call AllocateDSI( ISEDWU,        NSCM2,    0)
  Call AllocateDSI( IROUSE,        NSCM2,    0)
  Call AllocateDSI( ISBDLD,        NSCM2,    0)
  Call AllocateDSI( ISEDSCOR,      NSCM2,    0)
  Call AllocateDSI( ISLTAUC,       NSCM2,    0)
  Call AllocateDSI( ISNDEQ,        NSCM2,    0)
  Call AllocateDSI( ISNDM1,        NSCM2,    0)
  Call AllocateDSI( ISNDM2,        NSCM2,    0)
  Call AllocateDSI( IWRSPB,        NSCM2,    0)
  Call AllocateDSI( ISPROBDEP,     NSCM2,    0)
                                         
  Call AllocateDSI( COSEDHID,      NSTM2,  0.0)
  Call AllocateDSI( RSNDM,         NSTM2,  0.0)
  Call AllocateDSI( SDBLV,         NSTM2,  0.0)
  Call AllocateDSI( SDEN,          NSTM2,  0.0)               ! ***  SPECIFIC VOLUME OF EACH SEDIMENT CLASS (M3/G)
  Call AllocateDSI( SEDN,          NSTM2,  0.0)
  Call AllocateDSI( SEDO,          NSTM2,  0.0)
  Call AllocateDSI( SEDBO,         NSTM2,  0.0)
  Call AllocateDSI( SEDDIA,        NSTM2,  0.0)
  Call AllocateDSI( SEXP,          NSTM2,  0.0)
  Call AllocateDSI( SSG,           NSTM2,  0.0)
  Call AllocateDSI( TAUD,          NSTM2,  0.0)
  Call AllocateDSI( TAUN,          NSTM2,  0.0)
  Call AllocateDSI( TAUR,          NSTM2,  0.0)
  Call AllocateDSI( TCSHIELDS,     NSTM2,  0.0)
  Call AllocateDSI( TEXP,          NSTM2,  0.0)
  Call AllocateDSI( VDRDEPO,       NSTM2,  0.0)
  Call AllocateDSI( WRSPO,         NSTM2,  0.0)
  Call AllocateDSI( WSEDO,         NSTM2,  0.0)
  Call AllocateDSI( VDRRSPO,       NSTM2,  0.0)
  
  IF( ISTRAN(6) >= 1 .OR. ISTRAN(7) >= 1 .OR. ISBAL > 0 )THEN
    Call AllocateDSI( ACOEF,       LCM,      -KBM,     0.0)
    Call AllocateDSI( ALOW,        LCM,      -KBM+1,   0.0)
    Call AllocateDSI( BDENBED,     LCM,       KBM,     0.0)
    Call AllocateDSI( BDENBED1,    LCM,       KBM,     0.0)
    Call AllocateDSI( BDENBEDA,    LCM,       0.0)     
    Call AllocateDSI( BDENBEDA1,   LCM,       0.0)     
    Call AllocateDSI( BEDBINIT,    LCM,       KBM,     0.0)
    Call AllocateDSI( BEDBKDSV,    LCM,       KBM,     0.0)
    Call AllocateDSI( BEDDINIT,    LCM,       KBM,     0.0)
    Call AllocateDSI( BEDLINIT,    LCM,       KBM,     0.0)
    Call AllocateDSI( BEDPORSV,    LCM,       KBM,     0.0)
    Call AllocateDSI( BEDTHKSV,    LCM,       KBM,     0.0)
    Call AllocateDSI( BEDVDRSV,    LCM,       KBM,     0.0)
    Call AllocateDSI( BMNN,        LCM,      -KBM+1,   0.0)
    Call AllocateDSI( CBEDTOTAL,   LCM,       0.0)     
    Call AllocateDSI( COEFK,       LCM,       KBM,     0.0)
    Call AllocateDSI( COEFSK,      LCM,       KBM,     0.0)
    Call AllocateDSI( CQBEDLOADX,  LCM,       NSNM,    0.0)
    Call AllocateDSI( CQBEDLOADY,  LCM,       NSNM,    0.0)
    Call AllocateDSI( CSHIELDS50,  LCM,       0.0)     
    Call AllocateDSI( CUPP,        LCM,      -KBM+1,   0.0)
    Call AllocateDSI( DSTRSE,      LCM,       KBM,     0.0)
    Call AllocateDSI( DZBTR,       LCM,       KBM,     0.0)
    Call AllocateDSI( DZBTR1,      LCM,       KBM,     0.0)
    Call AllocateDSI( FRACCOH,     LCM,       KBM,     0.0)
    Call AllocateDSI( FRACNON,     LCM,       KBM,     0.0)
    Call AllocateDSI( GAMTMP,      LCM,      -(KBM+1), 0.0)
    Call AllocateDSI( HBED,        LCM,       KBM,     0.0)
    Call AllocateDSI( HBED1,       LCM,       KBM,     0.0)
    Call AllocateDSI( HYDCN,       LCM,       KBM,     0.0)
                                             
    Call AllocateDSI( ISEDBU,      NSCM2,     0)
    Call AllocateDSI( ISNDBU,      NSNM,      0)
    Call AllocateDSI( ISNDWU,      NSNM,      0)
    Call AllocateDSI( ISDBLDIR,    LCM,       0)
                                             
    Call AllocateDSI( JSS3DSED,    NSCM2,     0)
    Call AllocateDSI( JSS3DSND,    NSNM,      0)
    Call AllocateDSI( JSS3DTOX,    NTXM,      0)
    Call AllocateDSI( PEXP,        LCM,       NSNM,             0.0)
    Call AllocateDSI( PHID,        LCM,       NSNM,             0.0)
    Call AllocateDSI( QSBDLDIN,    LCM,       NSNM,             0.0)                ! *** BEDLOAD FLUX IN  DUE TO FIXING BOUNDARY CONDITION CELLS TO ZERO BEDLOAD DELTA  (G/S)
    Call AllocateDSI( QSBDLDOT,    LCM,       MAX(NSNM, NSCM2), 0.0)    ! *** BEDLOAD FLUX OUT DUE TO FIXING BOUNDARY CONDITION CELLS TO ZERO BEDLOAD DELTA  (G/S)
    Call AllocateDSI( QSBDLDX,     LCM,       MAX(NSNM, NSCM2), 0.0)    ! *** U FACE SND FLUX DUE TO BEDLOAD (G/S)
    Call AllocateDSI( QSBDLDY,     LCM,       MAX(NSNM, NSCM2), 0.0)    ! *** V FACE SND FLUX DUE TO BEDLOAD (G/S)
    Call AllocateDSI( QSBDLDP,     LCM,       0.0)                      ! *** CELL CENTER BED LOAD TRANSPORT RATE (G/S)
    Call AllocateDSI( QSBDTOP,     LCM,       0.0)                      ! *** VOLUME OF SEDIMENT BED EXCHANGE (M/S)
    Call AllocateDSI( QSEDBED,     LCM,       KBM,              NSTM2,  0.0)
    Call AllocateDSI( QSEDBED1,    LCM,       KBM,              NSTM2,  0.0)
    Call AllocateDSI( QSEDBEDA,    LCM,       NSTM2,            0.0)
    Call AllocateDSI( QSEDBEDA1,   LCM,       NSTM2,            0.0)
                                             
    Call AllocateDSI( SEDDIA50,    LCM,       KBM, 0.0)
    Call AllocateDSI( SEDDIA90,    LCM,       KBM, 0.0)
                                             
    Call AllocateDSI( SEDB,        LCM,       KBM,        NSCM2, 0.0)
    Call AllocateDSI( SEDB1,       LCM,       KBM,        NSCM2, 0.0)
    Call AllocateDSI( SEDBT,       LCM,       KBM,        0.0)
    Call AllocateDSI( SEDFPA,      LCM,       NSCM2,      0.0)
    Call AllocateDSI( SEDT,        LCM,       KCM,        0.0)
                                                         
    Call AllocateDSI( SNDB,        LCM,       KBM,        NSNM, 0.0)
    Call AllocateDSI( SNDB1,       LCM,       KBM,        NSNM, 0.0)
    Call AllocateDSI( SNDBT,       LCM,       KBM,        0.0)
    Call AllocateDSI( SNDFPA,      LCM,       NSNM,       0.0)
    Call AllocateDSI( SNDT,        LCM,       KCM,        0.0)
                                             
    Call AllocateDSI( TAUBSED,     LCM,       0.0)                ! *** Grain separated density normalized bed shear stress (m2/s2)
    Call AllocateDSI( TAUBSND,     LCM,       0.0)                ! *** Grain separated density normalized bed shear stress (m2/s2)
    Call AllocateDSI( TAUCRCOH,    LCM,       KBM,     0.0)
    Call AllocateDSI( TAURB,       LCM,       KBM,     0.0)
    Call AllocateDSI( TAUDS,       LCM,       0.0)     
    Call AllocateDSI( TAUNS,       LCM,       KBM,     0.0)
    Call AllocateDSI( TAURS,       LCM,       KBM,     0.0)
    Call AllocateDSI( TEXPS,       LCM,       KBM,     0.0)
                                                      
    Call AllocateDSI( VDRBED,      LCM,       KBM,     0.0)
    Call AllocateDSI( VDRBED1,     LCM,       KBM,     0.0)
    Call AllocateDSI( VDRBED2,     LCM,       KBM,     0.0)
    Call AllocateDSI( VDRBEDA,     LCM,       0.0)     
    Call AllocateDSI( VDRBEDSED,   LCM,       KBM,     0.0)
    Call AllocateDSI( VDRBEDSND,   LCM,       KBM,     0.0)
    Call AllocateDSI( VDRHBEDA1,   LCM,       0.0)     
    Call AllocateDSI( VFRBED,      LCM,       KBM,     NSTM2,  0.0)
    Call AllocateDSI( VFRBED1,     LCM,       KBM,     NSTM2,  0.0)
    Call AllocateDSI( VOLBW2,      LCM,       KBM,     0.0)
    Call AllocateDSI( VOLBW3,      LCM,       KBM,     0.0)
    Call AllocateDSI( WSETA,       LCM,      -KCM,     NSTM2,  0.0)
    Call AllocateDSI( WRSPB,       LCM,       KBM,     0.0)
    Call AllocateDSI( WRSPBA,      LCM,       0.0)     
    Call AllocateDSI( WRSPS,       LCM,       KBM,     0.0)
    Call AllocateDSI( WRSPSA,      LCM,       0.0)     
    Call AllocateDSI( ZBEDC,       LCM,       KBM,     0.0)
    Call AllocateDSI( ZBEDG,       LCM,      -KBM,     0.0)
    Call AllocateDSI( ZBEDGT,      LCM,       0.0)     
    IF( ISBEDSTR == 3 )THEN                           
      Call AllocateDSI( ZBRSED,    LCM,       0.0)     
    ELSE                                              
      Call AllocateDSI( ZBRSED,    1,         0.0)     
    ENDIF                                             
    Call AllocateDSI( ZELBED,      LCM,       KBM,     0.0)
    Call AllocateDSI( ZELBED1,     LCM,       KBM,     0.0)
    Call AllocateDSI( ZELBEDA,     LCM,       0.0)
    Call AllocateDSI( ZELBEDA1,    LCM,       0.0)
                                             
    Call AllocateDSI( PARTMIXZ,    LCM,       KBM,     0.0)
    Call AllocateDSI( PMXDEPTH,    NPMXPTSM,  NPMXZM,  0.0)
    Call AllocateDSI( PMXCOEF,     NPMXPTSM,  NPMXZM,  0.0)
    Call AllocateDSI( PORBED,      LCM,       KBM,     0.0)
    Call AllocateDSI( PORBED1,     LCM,       KBM,     0.0)
    Call AllocateDSI( QCOEF,       LCM,      -KBM,     0.0)
    Call AllocateDSI( QWTRBED,     LCM,      -KBM,     0.0)                ! *** VOLUME OF WATER EXCHANGE BETWEEN SEDIMENT LAYERS (M/S)
    Call AllocateDSI( RRHS,        LCM,      -KBM+1,   0.0)
    Call AllocateDSI( RSEDERE2T,   NSCM2,     0.0)
    Call AllocateDSI( RSEDERE2TB,  NSCM2,     0.0)
    Call AllocateDSI( RSEDERE2TW,  NSCM2,     0.0)
    Call AllocateDSI( RSEDERO2T,   NSCM2,     0.0)
    Call AllocateDSI( RSEDERO2TB,  NSCM2,     0.0)
    Call AllocateDSI( RSEDERO2TW,  NSCM2,     0.0)
    Call AllocateDSI( RSNDERE2T,   NSNM,      0.0)
    Call AllocateDSI( RSNDERE2TB,  NSNM,      0.0)
    Call AllocateDSI( RSNDERE2TW,  NSNM,      0.0)
    Call AllocateDSI( RSNDERO2T,   NSNM,      0.0)
    Call AllocateDSI( RSNDERO2TB,  NSNM,      0.0)
    Call AllocateDSI( RSNDERO2TW,  NSNM,      0.0)
    Call AllocateDSI( SDENAVG,     LCM,       KBM,     0.0)
    Call AllocateDSI( SGSM1,       LCM,       KBM,     0.0)
    Call AllocateDSI( SIGPHI,      LCM,       KBM,     0.0)
    Call AllocateDSI( STDOCB,      LCM,       KBM,     0.0)
    Call AllocateDSI( STDOCW,      LCM,       KCM,     0.0)
    Call AllocateDSI( STFPOCB,     LCM,       KBM,     NSTM2,  0.0)
    Call AllocateDSI( STFPOCW,     LCM,       KCM,     NSTM2,  0.0)
    Call AllocateDSI( STPOCB,      LCM,       KBM,     0.0)
    Call AllocateDSI( STRSE,       LCM,       KBM,     0.0)
                                  
    ! *** BANK EROSION            
    Call AllocateDSI( IBANKBE,     NBEPAIRM,  0)
    Call AllocateDSI( JBANKBE,     NBEPAIRM,  0)
    Call AllocateDSI( ICHANBE,     NBEPAIRM,  0)
    Call AllocateDSI( JCHANBE,     NBEPAIRM,  0)
    Call AllocateDSI( NBESERN,     NBEPAIRM,  0)
    Call AllocateDSI( MBESER,      NBESERM,   0)
    Call AllocateDSI( MBETLAST,    NBESERM,   0)
    Call AllocateDSI( LPMXZ,       LCM,       0)
  ENDIF

  ! *** CALMMT/RESIDUAL/MODEL LINKAGES VARIABLES
  IF( ISSSMMT > 0 .OR. ISWASP > 0 )THEN
    Call AllocateDSI( EVPGLPF,     LCM,       0.0)                     ! *** MMT - AVERAGE TRANSPIRATION RATE (M3/S)
    Call AllocateDSI( EVPSLPF,     LCM,       0.0)                     ! *** MMT - AVERAGE EVAPORATION RATE (M3/S)
    Call AllocateDSI( GWLPF,       LCM,       0.0)                     ! *** MMT - AVERAGE GROUNDWATER ELEVATION BELOW CELL (M)
    Call AllocateDSI( HLPF,        LCM,       0.0)                     ! *** MMT - AVERAGE DEPTH
    Call AllocateDSI( QSUMELPF,    LCM,       0.0)
    Call AllocateDSI( QSUMLPF,     LCM,       KCM,  0.0)
    Call AllocateDSI( RAINLPF,     LCM,       0.0)                     ! *** MMT - ACCUMULATED RAINFALL (M3/S)
    Call AllocateDSI( RINFLPF,     LCM,       0.0)                     ! *** ISGWIE > - MMT -ACCUMULATED INFILTRATION RATE (M3/S)
    Call AllocateDSI( SALLPF,      LCM,       KCM,  0.0)
    Call AllocateDSI( SFLLPF,      LCM,       KCM,  0.0)
    Call AllocateDSI( TEMLPF,      LCM,       KCM,  0.0)
    Call AllocateDSI( UELPF,       LCM,       0.0)                     ! *** MMT - AVERAGE DEPTH AVERAGED U VELOCITY
    Call AllocateDSI( VELPF,       LCM,       0.0)                     ! *** MMT - AVERAGE DEPTH AVERAGED V VELOCITY
    Call AllocateDSI( WLPF,        LCM,      -KCM,  0.0)
    Call AllocateDSI( WTLPF,       LCM,       KCM,  0.0)

    IF( ISTRAN(5) > 0 )THEN
      Call AllocateDSI( TOXBLPF,   LCM,       KBM,  NTXM,     0.0)
      Call AllocateDSI( TOXLPF,    LCM,       KCM,  NTXM,     0.0)
      Call AllocateDSI( TXPFLPF,   LCM,       KCM,  NSTM2+2,  NTXM,  0.0)  ! ***
    ENDIF
    IF( ISTRAN(6) > 0 )THEN
      Call AllocateDSI( SEDBLPF,   LCM,       KBM,  NSCM2,    0.0)
      Call AllocateDSI( SEDBTLPF,  LCM,       KBM,  0.0)      
      Call AllocateDSI( SEDLPF,    LCM,       KCM,  NSCM2,    0.0)
      Call AllocateDSI( SEDTLPF,   LCM,       KCM,  0.0)
    ENDIF
    IF( ISTRAN(7) > 0 )THEN
      Call AllocateDSI( SNDBLPF,   LCM,       KBM,  NSNM,     0.0)
      Call AllocateDSI( SNDBTLPF,  LCM,       KBM,  0.0)      
      Call AllocateDSI( SNDLPF,    LCM,       KCM,  NSNM,     0.0)
      Call AllocateDSI( SNDTLPF,   LCM,       KCM,  0.0)
    ENDIF
  ENDIF

  ! ** WATER QUALITY VARIABLES
  Call AllocateDSI( WQKEB,    1, 0.0)
  IF( ISTRAN(8) >= 1 )THEN
    Call WQ_Allocate
    IF( IWQBEN > 0 ) Call SD_Allocate
    IF( IWQZPL > 0 ) Call Zoo_Allocate
  ENDIF   ! *** END OF WQ VARIABLE DECLARATIONS

  IF( ISWQFLUX == 1 )THEN
    Call AllocateDSI( ABEFF,       LCM,       KCM,     0.0)
    Call AllocateDSI( ABLPF,       LCM,       KCM,     0.0)
    Call AllocateDSI( ACCWFLD,     LCM,       2,       0.0)
    Call AllocateDSI( AHULPF,      LCM,       KCM,     0.0)
    Call AllocateDSI( AHVLPF,      LCM,       KCM,     0.0)
    Call AllocateDSI( DYELPF,      LCM,       KCM,     NDYM,  0.0)
                                                     
    Call AllocateDSI( ISPV,        LCM,       10,        0)
    Call AllocateDSI( IVPV,        LCM,       10,        0)
    Call AllocateDSI( JSPV,        LCM,       10,        0)
    Call AllocateDSI( JVPV,        LCM,       10,        0)
                                                     
    Call AllocateDSI( UHLPF,       LCM,       KCM,     0.0)
    Call AllocateDSI( UIRT,        LCM,       KCM,     0.0)
    Call AllocateDSI( ULPF,        LCM,       KCM,     0.0)
    Call AllocateDSI( ULSHA,       KCM,       MLM,     0.0)
    Call AllocateDSI( UTLPF,       LCM,       KCM,     0.0)
    Call AllocateDSI( UTLSHA,      KCM,       MLM,     0.0)
    Call AllocateDSI( UVPT,        LCM,       KCM,     0.0)
    Call AllocateDSI( U1DT1,       KCM,       MLM,     0.0)
                                                     
    Call AllocateDSI( VHLPF,       LCM,       KCM,     0.0)
    Call AllocateDSI( VIRT,        LCM,       KCM,     0.0)
    Call AllocateDSI( VLPF,        LCM,       KCM,     0.0)
    Call AllocateDSI( VLSHA,       KCM,       MLM,     0.0)
    Call AllocateDSI( VTLPF,       LCM,       KCM,     0.0)
    Call AllocateDSI( VVPT,        LCM,       KCM,     0.0)
    Call AllocateDSI( V1DT1,       KCM,       MLM,     0.0)
                                                     
    Call AllocateDSI( WIRT,        LCM,       KCM,     0.0)
  ENDIF                           
                                  
  IF( ISWASP > 0 )THEN            
    Call AllocateDSI( LCEFDC,      LCM*KCM,   0)
    Call AllocateDSI( LCHNC,       KCM*LCM,   10,       0)
    Call AllocateDSI( NCHNC,       KCM*LCM,   0)
  ELSE                            
    Call AllocateDSI( LCEFDC,      1,         0)
    Call AllocateDSI( LCHNC,       1,         1,        0)
    Call AllocateDSI( NCHNC,      -1,         0)
  ENDIF
  
  ! *** Set constants for M2 tidal cycle harmonic analysis
  IF( ISHTA > 0 )THEN
    Call AllocateDSI( WC,       NTSPTC2,    0.0)
    Call AllocateDSI( WC2,      NTSPTC2,    0.0)
    Call AllocateDSI( WS,       NTSPTC2,    0.0)
    Call AllocateDSI( WS2,      NTSPTC2,    0.0)
  ENDIF
  
  ! Begin SEDZLJ variables
  Call AllocateDSI( FWVTP,          LCM,      0.0)
  Call AllocateDSI( FWDIR,          LCM,      16,      0.0)
  IF( LSEDZLJ )THEN
    Call AllocateDSI( ALPHA_PX,     LCM,    0.0)
    Call AllocateDSI( ALPHA_PY,     LCM,    0.0)
    Call AllocateDSI( ALPHA_RX,     LCM,    NSCM2,     0.0)
    Call AllocateDSI( ALPHA_RY,     LCM,    NSCM2,     0.0)
    Call AllocateDSI( BLFLAG,       LCM,    NSCM2,     0)
    Call AllocateDSI( BULKDENS,     KB,     LCM,       0.0)
    Call AllocateDSI( D50,          NSCM2,  0.0)
    Call AllocateDSI( D50AVG,       LCM,    0.0)
    Call AllocateDSI( DEPO,         LCM,    0.0)
    Call AllocateDSI( DISTAR,       NSCM2,  0.0)
    Call AllocateDSI( DZBL,         LCM,    NSCM2,      0.0)
    !ALLOCATE(DZBL_LAST(LCM, NS    CM2, 0.0)
    Call AllocateDSI( DWS,          NSCM2,  0.0)
    Call AllocateDSI( DWSIN,        NSCM2,  0.0)
    Call AllocateDSI( ESUS,         LCM,    0.0)
    Call AllocateDSI( ETOTO,        LCM,    0.0)
    Call AllocateDSI( HPCM,         LCM,    0.0)
    Call AllocateDSI( KPART,        NTXM,   0.0)
    Call AllocateDSI( LAYERACTIVE,  KB,     LCM,      0)
    Call AllocateDSI( NCORENO,      IC,     JC,       0)
    Call AllocateDSI( PERSED,       NSCM, KB, LCM,  0.0)
    Call AllocateDSI( PSUS,         LCM,    NSCM,    0.0)
    Call AllocateDSI( QBLFLUX,      LCM,    NSCM,    0.0)
    Call AllocateDSI( SCND,         NSICM,  0.0)      
    Call AllocateDSI( SH_SCALE,     LCM,    0.0)      
    Call AllocateDSI( SSGI,         NSCM2,  0.0)      
    Call AllocateDSI( STWVHT,       LCM,    200,      0.0)
    Call AllocateDSI( STWVTP,       LCM,    200,      0.0)
    Call AllocateDSI( STWVDR,       LCM,    200,      0.0)
    Call AllocateDSI( TAU,          LCM,    0.0)      
    Call AllocateDSI( TAUCOR,       KB+1,   LCM,      0.0)
    Call AllocateDSI( TAUCRITE,     NSICM,  0.0)
    Call AllocateDSI( TCRE,         NSCM,   0.0)
    Call AllocateDSI( TCRSUS,       NSCM,   0.0)
    Call AllocateDSI( TRANS,        LCM,    NSCM2,    0.0)
    Call AllocateDSI( TSED,         KB,     LCM,      0.0)
    Call AllocateDSI( TSED0,        KB,     LCM,      0.0)
    Call AllocateDSI( TSET0T,       LCM,    0.0)      
    Call AllocateDSI( TSEDT,        LCM,    0.0)      
    Call AllocateDSI( USW,          LCM,    NSCM,     0.0)
    Call AllocateDSI( WVANG,        LCM,    0.0)      
    IF( ICALC_BL > 0 )THEN                           
      Call AllocateDSI( BLVEL,      LCM,    NSCM,     0.0)
      Call AllocateDSI( CBL,        LCM,    NSCM,     0.0)
      Call AllocateDSI( DBL,        LCM,    NSCM,     0.0)
      Call AllocateDSI( EBL,        LCM,    NSCM,     0.0)
      Call AllocateDSI( UBL,        LCM,    NSCM,     0.0)
      Call AllocateDSI( VBL,        LCM,    NSCM,     0.0)
      IF( ISTRAN(5) > 0 )THEN                        
        Call AllocateDSI( CBLTOX,   LCM,    NTXM,     0.0)
        Call AllocateDSI( CBLTXCON, LCM,    NSCM,     NTXM,   0.0)
      ENDIF
    ENDIF
  ENDIF
  ! End SEDZLJ variables

  ! *** OMP DECLARATIONS
  Call AllocateDSI( CD,         LCM,       KCM,   NTHREADS,   0.0)
  Call AllocateDSI( FQC,        LCM,       KCM,   NTHREADS,   0.0)
  Call AllocateDSI( FUHVD,      LCM,       KCM,   NTHREADS,   0.0)
  Call AllocateDSI( FVHVD,      LCM,       KCM,   NTHREADS,   0.0)
  Call AllocateDSI( FWVV,       LCM,      -KCM,   NTHREADS,   0.0)
  Call AllocateDSI( FQCPAD,     LCM,       KCM,   NTHREADS,   0.0)
  Call AllocateDSI( QSUMNAD,    LCM,       KCM,   NTHREADS,   0.0)
  Call AllocateDSI( QSUMPAD,    LCM,       KCM,   NTHREADS,   0.0)
  Call AllocateDSI( DUU,        LCM,       KCM,   NTHREADS,   0.0)
  Call AllocateDSI( DVV,        LCM,       KCM,   NTHREADS,   0.0)
  Call AllocateDSI( POS,        LCM,       KCM,   NTHREADS,   0.0)
  Call AllocateDSI( UUUU,       LCM,       KCM,   NTHREADS,   0.0)
  Call AllocateDSI( VVVV,       LCM,       KCM,   NTHREADS,   0.0)
  Call AllocateDSI( WWWW,       LCM,      -KCM,   NTHREADS,   0.0)
  Call AllocateDSI( CONQ,       LCM,       KCM,   NTHREADS,   0.0)
  Call AllocateDSI( CMAX,       LCM,       KCM,   NTHREADS,   0.0)
  Call AllocateDSI( CMIN,       LCM,       KCM,   NTHREADS,   0.0)
  Call AllocateDSI( CONTD,      LCM,       KCM,   NTHREADS,   0.0)
  Call AllocateDSI( CONTMN,     LCM,       KCM,   NTHREADS,   0.0)
  Call AllocateDSI( CONTMX,     LCM,       KCM,   NTHREADS,   0.0)

  ! Begin MHK variables SCJ
  Call AllocateDSI( IJLTURB,    TCOUNT,    3,     0)
  Call AllocateDSI( CTMHK,      MHKTYP,    0.0)
  Call AllocateDSI( CDSUP,      MHKTYP,    0.0)
  Call AllocateDSI( DENMHK,     MHKTYP,    0.0)            ! *** DENSITY OF MHK DEVICES (#/CELL)
  Call AllocateDSI( ESUP,       TCOUNT,    LCM,   0.0)     ! *** zero the allocatable arrays for MHK energy generation
  Call AllocateDSI( EMHK,       TCOUNT,    LCM,   0.0)     ! *** zero the allocatable arrays for support energy dissipatio
  Call AllocateDSI( FXMHK,      LCM,       KCM,   0.0)     ! *** X"FORCE" FOR HORIZONTAL ADVECTION CALCULATIONS FROM MHK DEVICE
  Call AllocateDSI( FXMHKE,     LCM,       0.0)            ! *** COLUMN X"FORCE" FOR MOMENTUM CALCULATIONS FROM MHK DEVICE
  Call AllocateDSI( FXSUP,      LCM,       KCM,   0.0)     ! *** Y"FORCE" FOR HORIZONTAL ADVECTION CALCULATIONS FROM MHK DEVICE
  Call AllocateDSI( FXSUPE,     LCM,       0.0)            ! *** COLUMN Y"FORCE" FOR MOMENTUM CALCULATIONS FROM MHK DEVICE
  Call AllocateDSI( FYMHK,      LCM,       KCM,   0.0)     ! *** X"FORCE" FOR HORIZONTAL ADVECTION CALCULATIONS FROM MHK SUPPORT
  Call AllocateDSI( FYMHKE,     LCM,       0.0)            ! *** COLUMN X"FORCE" FOR MOMENTUM CALCULATIONS FROM MHK SUPPORT
  Call AllocateDSI( FYSUP,      LCM,       KCM,   0.0)     ! *** Y"FORCE" FOR HORIZONTAL ADVECTION CALCULATIONS FROM MHK SUPPORT
  Call AllocateDSI( FYSUPE,     LCM,       0.0)            ! *** COLUMN Y"FORCE" FOR MOMENTUM CALCULATIONS FROM MHK DEVICE
  Call AllocateDSI( PMHK,       LCM,       KCM,   0.0)     ! *** array that accumulates layer-wise MHK power in x direction
  Call AllocateDSI( PSUP,       LCM,       KCM,   0.0)     ! *** array that accumulates layer-wise MHK support power in x direction 
  Call AllocateDSI( VMAXCUT,    MHKTYP,    0.0)   
  Call AllocateDSI( VMINCUT,    MHKTYP,    0.0)   
  Call AllocateDSI( WIDTHMHK,   MHKTYP,    0.0)   
  Call AllocateDSI( WIDTHSUP,   MHKTYP,    0.0)   
  Call AllocateDSI( ZMAXMHK,    MHKTYP,    LCM,   0.0)
  Call AllocateDSI( ZMINMHK,    MHKTYP,    LCM,   0.0)
  Call AllocateDSI( ZMAXSUP,    MHKTYP,    LCM,   0.0)
  Call AllocateDSI( ZMINSUP,    MHKTYP,    LCM,   0.0)

  ! *** ALLOCATE MEMORY FOR VARIABLE TO STORE CONCENTRATIONS AT OPEN BOUNDARIES
  Call AllocateDSI( FBESER,         NBEPAIRM,  0.0)
  Call AllocateDSI( BESERT,         NBESERM,   0.0)
  Call AllocateDSI( FWCBESERT,      NBESERM,   0.0)
  Call AllocateDSI( TCBESER,        NBESERM,   0.0)
  Call AllocateDSI( TABESER,        NBESERM,   0.0)
  Call AllocateDSI( TBESER,         NDBESER,   NBESERM,  0.0)
  Call AllocateDSI( BESER,          NDBESER,   NBESERM,  0.0)
  Call AllocateDSI( FWCBESER,       NDBESER,   NBESERM,  0.0)
  Call AllocateDSI( QSBDTOPBEBKB,   LCM,       0.0)
  Call AllocateDSI( QSBDTOPBECHB,   LCM,       0.0)
  Call AllocateDSI( QSBDTOPBECHW,   LCM,       0.0)
  Call AllocateDSI( QWBDTOPBEBKB,   LCM,       0.0)
  Call AllocateDSI( QWBDTOPBECHB,   LCM,       0.0)
  Call AllocateDSI( QWBDTOPBECHW,   LCM,       0.0)
  Call AllocateDSI( SEDFBEBKB,      LCM,       NSCM2,    0.0)
  Call AllocateDSI( SEDFBECHB,      LCM,       NSCM2,    0.0)
  Call AllocateDSI( SEDFBECHW,      LCM,       NSCM2,    0.0)
  Call AllocateDSI( SNDFBEBKB,      LCM,       NSNM,     0.0)
  Call AllocateDSI( SNDFBECHB,      LCM,       NSNM,     0.0)
  Call AllocateDSI( SNDFBECHW,      LCM,       NSNM,     0.0)

  ! *** VARIABLES FOR QCTL NQCTYP=3 & 4
  Call AllocateDSI( LOWCHORDU,      NQCTL,     0.0)
  Call AllocateDSI( LOWCHORDV,      NQCTL,     0.0)
  Call AllocateDSI( NLOWCHORD,      NQCTL,     0)
  Call AllocateDSI( SAVESUB,        2,         NQCTL,    0.0)
  Call AllocateDSI( SAVESVB,        2,         NQCTL,    0.0)

  ! *** HYDRAULIC STRUCTURE EQUATIONS
  IF( NHYDST > 0 )THEN
    Call AllocateDSI( HS_LENGTH,    NHYDST,    0.0)
    Call AllocateDSI( HS_XSTYPE,    NHYDST,      0)
    Call AllocateDSI( HS_REVERSE,   NHYDST,      0)
    Call AllocateDSI( HS_WIDTH,     NHYDST,    0.0)
    Call AllocateDSI( HS_HEIGHT,    NHYDST,    0.0)
    Call AllocateDSI( HS_MANN,      NHYDST,    0.0)
    Call AllocateDSI( HS_ANGLE,     NHYDST,    0.0)
    Call AllocateDSI( HS_USELEV,    NHYDST,    0.0)
    Call AllocateDSI( HS_DSELEV,    NHYDST,    0.0)
    Call AllocateDSI( HS_COEFF,     NHYDST,    4,   0.0)
  ENDIF

  
  ! *** Macrophyte/vegetation
  Call AllocateDSI( MAC_CELL, LCM, .FALSE.)
  
  ! *** SIGMA-Z HSTRUCT
  Call AllocateDSI( KSZ,        LCM,     1)
  Call AllocateDSI( KSZU,       LCM,     1)
  Call AllocateDSI( KSZV,       LCM,     1)
  Call AllocateDSI( BI1W,       LCM,   0.0)
  Call AllocateDSI( BI2W,       LCM,   0.0)
  Call AllocateDSI( BEW,        LCM,   0.0)
  Call AllocateDSI( BI1S,       LCM,   0.0)
  Call AllocateDSI( BI2S,       LCM,   0.0)
  Call AllocateDSI( BES,        LCM,   0.0)
  IF( IGRIDV > 0 .OR. ISBLOCKED > 0 )THEN
    Call AllocateDSI( BELVE,      LCM,   0.0)
    Call AllocateDSI( BELVW,      LCM,   0.0)
    Call AllocateDSI( BELVN,      LCM,   0.0)
    Call AllocateDSI( BELVS,      LCM,   0.0)
    Call AllocateDSI( BE,         LCM,   KCM,   0.0)
    Call AllocateDSI( BW,         LCM,   KCM,   0.0)
    Call AllocateDSI( BN,         LCM,   KCM,   0.0)
    Call AllocateDSI( BS,         LCM,   KCM,   0.0)
    Call AllocateDSI( BEE,        LCM,   0.0)
    Call AllocateDSI( BEN,        LCM,   0.0)
    Call AllocateDSI( BI1E,       LCM,   0.0)
    Call AllocateDSI( BI1N,       LCM,   0.0)
    Call AllocateDSI( BI2E,       LCM,   0.0)
    Call AllocateDSI( BI2N,       LCM,   0.0)
    Call AllocateDSI( HPE,        LCM,   0.0)
    Call AllocateDSI( HPW,        LCM,   0.0)
    Call AllocateDSI( HPN,        LCM,   0.0)
    Call AllocateDSI( HPS,        LCM,   0.0)
    Call AllocateDSI( KSZE,       LCM,     1)
    Call AllocateDSI( KSZW,       LCM,     1)
    Call AllocateDSI( KSZN,       LCM,     1)
    Call AllocateDSI( KSZS,       LCM,     1)
    Call AllocateDSI( SGZKE,      KCM,   LCM,   0.0)
    Call AllocateDSI( SGZKW,      KCM,   LCM,   0.0)
    Call AllocateDSI( SGZKN,      KCM,   LCM,   0.0)
    Call AllocateDSI( SGZKS,      KCM,   LCM,   0.0)
    Call AllocateDSI( SGZE,       LCM,   KCM,   0.0)
    Call AllocateDSI( SGZW,       LCM,   KCM,   0.0)
    Call AllocateDSI( SGZN,       LCM,   KCM,   0.0)
    Call AllocateDSI( SGZS,       LCM,   KCM,   0.0)
    Call AllocateDSI( ZE,         LCM,  -KCM,   0.0)
    Call AllocateDSI( ZW,         LCM,  -KCM,   0.0)
    Call AllocateDSI( ZN,         LCM,  -KCM,   0.0)
    Call AllocateDSI( ZS,         LCM,  -KCM,   0.0)
    Call AllocateDSI( ZZE,       -KCM,   LCM,   0.0)
    Call AllocateDSI( ZZW,       -KCM,   LCM,   0.0)
    Call AllocateDSI( ZZN,       -KCM,   LCM,   0.0)
    Call AllocateDSI( ZZS,       -KCM,   LCM,   0.0)
  ENDIF
  Call AllocateDSI( DZIGSD4U, LCM,   KCM,   0.0)
  Call AllocateDSI( DZIGSD4V, LCM,   KCM,   0.0)
                                          
  Call AllocateDSI( DZC,      LCM,   KCM,   0.0)
  Call AllocateDSI( DZCK,     KCM,   0.0)  
  Call AllocateDSI( DZCU,     LCM,   KCM,   0.0)
  Call AllocateDSI( DZCV,     LCM,   KCM,   0.0)
  Call AllocateDSI( DZG,      LCM,   KCM,   0.0)
  Call AllocateDSI( DZGU,     LCM,   KCM,   0.0)
  Call AllocateDSI( DZGV,     LCM,   KCM,   0.0)
  Call AllocateDSI( LKSZ,     LCM,   KCM,   .false.)
                                          
  Call AllocateDSI( CDZDU,    LCM,   KCM,   0.0)
  Call AllocateDSI( CDZDV,    LCM,   KCM,   0.0)
  Call AllocateDSI( CDZFU,    LCM,   KCM,   0.0)
  Call AllocateDSI( CDZFV,    LCM,   KCM,   0.0)
  Call AllocateDSI( CDZLU,    LCM,   KCM,   0.0)
  Call AllocateDSI( CDZLV,    LCM,   KCM,   0.0)
  Call AllocateDSI( CDZMU,    LCM,   KCM,   0.0)
  Call AllocateDSI( CDZMV,    LCM,   KCM,   0.0)
  Call AllocateDSI( CDZRU,    LCM,   KCM,   0.0)
  Call AllocateDSI( CDZRV,    LCM,   KCM,   0.0)
  Call AllocateDSI( CDZUU,    LCM,   KCM,   0.0)
  Call AllocateDSI( CDZUV,    LCM,   KCM,   0.0)
                                          
  Call AllocateDSI( SUB3D,   -LCM,   KCM,   0.0)
  Call AllocateDSI( SUB3DO,  -LCM,   KCM,   0.0)
  Call AllocateDSI( SVB3D,   -LCM,   KCM,   0.0)
  Call AllocateDSI( SVB3DO,  -LCM,   KCM,   0.0)
                                          
  Call AllocateDSI( SGZU,     LCM,   KCM,   0.0)
  Call AllocateDSI( SGZV,     LCM,   KCM,   0.0)
  Call AllocateDSI( FSGZU,    LCM,   KCM,   0.0)
  Call AllocateDSI( FSGZV,    LCM,   KCM,   0.0)
  Call AllocateDSI( LSGZU,    LCM,   KCM,   .false.)
  Call AllocateDSI( LSGZV,    LCM,   KCM,   .false.)
                                          
  Call AllocateDSI( HPK,      LCM,   KCM,   0.0)
  Call AllocateDSI( HPKI,     LCM,   KCM,   0.0)
  Call AllocateDSI( H1PK,     LCM,   KCM,   0.0)
  Call AllocateDSI( H2PK,     LCM,   KCM,   0.0)
  Call AllocateDSI( UHDY,     LCM,   KCM,   0.0)
  Call AllocateDSI( VHDX,     LCM,   KCM,   0.0)
  Call AllocateDSI( UHDY1,    LCM,   KCM,   0.0)
  Call AllocateDSI( VHDX1,    LCM,   KCM,   0.0)
  Call AllocateDSI( UHDY2,    LCM,   KCM,   0.0)
  Call AllocateDSI( VHDX2,    LCM,   KCM,   0.0)
  Call AllocateDSI( UHDYF,    LCM,   KCM,   0.0)
  Call AllocateDSI( VHDXF,    LCM,   KCM,   0.0)
  Call AllocateDSI( UHDYF1,   LCM,   KCM,   0.0)
  Call AllocateDSI( VHDXF1,   LCM,   KCM,   0.0)
  Call AllocateDSI( UHDYF2,   LCM,   KCM,   0.0)
  Call AllocateDSI( VHDXF2,   LCM,   KCM,   0.0)

  ! *** WET/DRY BYPASS VARIABLES
  Call AllocateDSI( LWET,     LCM, 0)
  Call AllocateDSI( LDRY,     LCM, 0)

  ! *** ATMOS
  IF( NASER >= 1 )THEN
    Call AllocateDSI( TCASER,    NASER,  0.0)
    Call AllocateDSI( TAASER,    NASER,  0.0)
    Call AllocateDSI( IRELH,     NASER,  0)
    Call AllocateDSI( MTSALAST,  NASER,  0)
  ENDIF

  ! *** WIND
  IF( NWSER >= 1 )THEN
    Call AllocateDSI( TCWSER,    NWSER,  0.0)
    Call AllocateDSI( TAWSER,    NWSER,  0.0)
    Call AllocateDSI( ISWDINT,   NWSER,  0)
    Call AllocateDSI( MTSWLAST,  NWSER,  0)
    Call AllocateDSI( WINDH,     NWSER,  0.0)
  ENDIF

  ! *** ICE
  IF( ISICE > 0 )THEN
    Call AllocateDSI( MITLAST,     NISER,   0)           ! *** ISICE=1  INPUT SERIES LAST INDEX FOR SERIES
    Call AllocateDSI( FRAZILICE,   LCM,     KCM,   0.0)  ! *** ISICE=4 FRAZIL ICE IN EACH CELL AND LAYER (M)
    Call AllocateDSI( FRAZILICE1,  LCM,     KCM,   0.0)  ! *** ISICE=4 FRAZIL ICE IN EACH CELL AND LAYER FOR PREVIOUS TIME STEP (M)
    Call AllocateDSI( ICECOVER,    LCM,     0.0)         ! *** ISICE>0 FRACTION OF ICE COVER FOR EACH CELL (M)
    Call AllocateDSI( ICERATE,     LCM,     0.0)         ! *** ISICE>2 WATER FLOW RATE TO/FROM WATER COLUMN (M3/S)
    Call AllocateDSI( ICETHICK,    LCM,     0.0)         ! *** ISICE>0 ICE THICKNESS FOR EACH CELL (M)
    Call AllocateDSI( ICETHICK1,   LCM,     0.0)         ! *** ISICE>0 ICE THICKNESS FOR EACH CELL FOR PREVIOUS TIME STEP (M)
    Call AllocateDSI( ICETEMP,     LCM,     0.0)         ! *** ISICE>0 ICE TEMPERATURE OF EACH CELL (M)
    Call AllocateDSI( ICEVOL,      LCM,     0.0)         ! *** ISICE>0 INCREMENTAL WATER VOLUMES FOR ICE FORMATION/MELT (M3)
    Call AllocateDSI( TCISER,      NISER,   0.0)         ! *** ISICE=1  INPUT SERIES TIME CONVERSION
    Call AllocateDSI( TAISER,      NISER,   0.0)         ! *** ISICE=1  INPUT SERIES (NOT USED)
    Call AllocateDSI( RICECOVT,    NISER,   0.0)         ! *** ISICE=1  INPUT ICE COVER AT CURRENT TIME
    Call AllocateDSI( RICETHKT,    NISER,   0.0)         ! *** ISICE=1  INPUT ICE THICKNESS AT CURRENT TIME
  ENDIF
  Call AllocateDSI( ICECELL,   LCM,  .false.)            ! *** ISICE>0  PERFORM ICE COMPUTATIONS
  Call AllocateDSI( RHOW,      LCM,  KCM,   0.0)         ! *** DENSITY OF WATER KG/M3, FROM CALBUOY

  IF( ISLSHA > 0 .OR. ISHTA >0 )THEN
    Call AllocateDSI( AMCP,     LCM,   0.0)
    Call AllocateDSI( AMCU,     LCM,   KCM,   0.0)
    Call AllocateDSI( AMCUE,    LCM,   0.0)   
    Call AllocateDSI( AMCV,     LCM,   KCM,   0.0)
    Call AllocateDSI( AMCVE,    LCM,   0.0)   
    Call AllocateDSI( AMPU,     MTM,   0.0)   
    Call AllocateDSI( AMPV,     MTM,   0.0)   
    Call AllocateDSI( AMSP,     LCM,   0.0)   
    Call AllocateDSI( AMSU,     LCM,   KCM,   0.0)
    Call AllocateDSI( AMSUE,    LCM,   0.0)   
    Call AllocateDSI( AMSV,     LCM,   KCM,   0.0)
    Call AllocateDSI( AMSVE,    LCM,   0.0)
  ENDIF

  ! *** BLOCKED LAYER FACE OPTION
  IF( NBLOCKED > 0 )THEN
    Call AllocateDSI( KBBU,        NBLOCKED,     0)
    Call AllocateDSI( KBBV,        NBLOCKED,     0)
    Call AllocateDSI( KTBU,        NBLOCKED,     0)
    Call AllocateDSI( KTBV,        NBLOCKED,     0)
    Call AllocateDSI( LBLOCKED,    NBLOCKED,     0)
    Call AllocateDSI( BLANCHORU,   NBLOCKED,   0.0)
    Call AllocateDSI( BLANCHORV,   NBLOCKED,   0.0)
    Call AllocateDSI( BLDRAFTUO,   NBLOCKED,   0.0)
    Call AllocateDSI( BLDRAFTVO,   NBLOCKED,   0.0)
    Call AllocateDSI( BLSILLU,     NBLOCKED,   0.0)
    Call AllocateDSI( BLSILLV,     NBLOCKED,   0.0)
    Call AllocateDSI( BLDRAFTU,    NBLOCKED,   0.0)
    Call AllocateDSI( BLDRAFTV,    NBLOCKED,   0.0)
  ENDIF

  ! *** Deprecated data assimilation
  Call AllocateDSI( ICCDA,      NLDAM,        0)      
  Call AllocateDSI( ICDA,       NLDAM,        0)      
  Call AllocateDSI( ITPCDA,     NLDAM,        0)
  Call AllocateDSI( JCCDA,      NLDAM,        0)
  Call AllocateDSI( JCDA,       NLDAM,        0)
  Call AllocateDSI( LCDA,       NLDAM,        0)
  Call AllocateDSI( NCSERA,     NLDAM,     NSTVM2,    0)
    
END SUBROUTINE VARALLOC

